"""Generate alembic/guild/guild_rls.sql from the initiative-RLS path registry.

The registry — which tables are initiative-scoped and how each resolves its
initiative — is the single source of truth in ``app.db.initiative_rls``. This
script is just the emitter: it stamps the uniform policy boilerplate (ENABLE /
FORCE RLS + DROP/CREATE × 4 commands, read vs write flag) around each table's
path. Adding an initiative-scoped table means adding a path THERE, then running:

    python scripts/gen_guild_rls.py        # writes alembic/guild/guild_rls.sql

``schema_provisioning.apply_guild_rls`` applies the result to guild_template +
every guild_<id>; ``guild_rls_test.py`` (and a CI step) fail if the committed
file drifts from this generator's output.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow ``python scripts/gen_guild_rls.py`` from backend/ to import the app.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db.initiative_rls import (  # noqa: E402
    INITIATIVE_PATHS,
    INITIATIVE_SCOPED_TABLES,
    PathBuilder,
)
from app.db.soft_delete_filter import SOFT_DELETE_TABLES  # noqa: E402

_OUT = Path(__file__).resolve().parents[1] / "alembic" / "guild" / "guild_rls.sql"

# Hard delete = purge, and only a guild admin may purge (the interactive endpoint
# 403s otherwise; the background auto-purge worker runs as app_admin/BYPASSRLS, so
# RLS — including this RESTRICTIVE policy — does not apply to it). We back that with
# a DB-layer RESTRICTIVE FOR DELETE guard so a stray non-admin DELETE is refused by
# Postgres, not just by app code. The source of truth for "which tables are
# soft-deletable" is SOFT_DELETE_TABLES (derived from the SoftDeleteMixin
# subclasses). The guard goes on EVERY soft-delete table, split by how RLS is
# already set up on the table:
#   - initiative-scoped soft-delete tables already ENABLE RLS (for the membership
#     gate), so the RESTRICTIVE policy is appended to their existing block.
#   - the guild-level soft-delete tables (initiatives, tags) are RLS-free; they get
#     a dedicated guard block that ENABLEs RLS solely to host the purge guard (see
#     _guild_level_guard_block — the access policy there is a deliberate allow-all,
#     NOT a membership gate; initiative is the gate, guilds gate at the schema).
_PURGE_GUARD_TABLES: frozenset[str] = (
    frozenset(SOFT_DELETE_TABLES) & INITIATIVE_SCOPED_TABLES
)
_GUILD_LEVEL_PURGE_TABLES: frozenset[str] = (
    frozenset(SOFT_DELETE_TABLES) - INITIATIVE_SCOPED_TABLES
)

# Admit only a routed guild admin (the GUC ``set_rls_context`` writes from the
# request's validated membership role; a break-glass full-admin is routed as a
# synthetic guild admin and also sets it). Matches the guild-admin leg of
# public.initiative_access exactly.
_PURGE_GUARD_PREDICATE = (
    "current_setting('app.current_guild_role'::text, true) = 'admin'::text"
)

_HEADER = """\
-- AUTOGENERATED by scripts/gen_guild_rls.py — DO NOT EDIT BY HAND.
-- Initiative-member-level RLS for the per-guild CONTENT tables. Schema-relative
-- (run with search_path = <guild_schema>, public). Idempotent.
--
-- The access RULE lives in ONE place, public.initiative_access (initiative member
-- OR guild admin OR PAM, read from the request GUCs); each policy below is just the
-- join that resolves a table's initiative id and defers to it. The per-table paths
-- are the single source of truth in app/db/initiative_rls.py (INITIATIVE_PATHS).
--
-- SCOPE: only INITIATIVE-scoped CONTENT tables are here, exactly
-- app.db.initiative_rls.INITIATIVE_SCOPED_TABLES. The STRUCTURAL initiative tables
-- (initiatives, initiative_members, initiative_roles, initiative_role_permissions)
-- and guild-level / own-row tables (app.db.tenancy.GUILD_LEVEL_TABLES) are NOT
-- initiative-member-scoped: they are guild-scoped by the schema boundary (the
-- membership table can't be gated by the membership check it backs without
-- recursing; own-row scoping would break co-member rosters). The app layer still
-- does finer filtering (e.g. the initiatives list shows member-only for non-admins).
--
-- To add a new initiative-scoped table: add a path to INITIATIVE_PATHS in
-- app/db/initiative_rls.py, then regenerate.
--
-- Soft-delete tables additionally carry a RESTRICTIVE FOR DELETE policy
-- (soft_delete_admin_purge): hard delete = purge, and only a routed guild admin
-- may. It is RESTRICTIVE, so it AND-combines with the PERMISSIVE delete policy
-- above — a write-member clears the latter but not this one. app_admin (the
-- auto-purge worker) bypasses RLS entirely. Source of truth for the table set is
-- app.db.soft_delete_filter.SOFT_DELETE_TABLES (the SoftDeleteMixin subclasses).
-- The guild-level soft-delete tables (initiatives, tags) are RLS-free, so they get
-- the guard via the dedicated section at the bottom of this file.
"""

# Header for the guild-level guard section (initiatives, tags).
_GUILD_LEVEL_SECTION = """\
-- ===========================================================================
-- Guild-level soft-delete tables: admin-only purge guard ONLY.
--
-- These tables are NOT initiative-membership-gated: initiative is the gate (its
-- content tables point AT it via initiative_access), and the initiative anchor
-- tables can't gate themselves; guilds gate at the SCHEMA level (SET ROLE), which
-- already isolates these rows. RLS is enabled here SOLELY to host the RESTRICTIVE
-- admin-only-purge guard, so the access policy (guild_level_open) is a deliberate
-- allow-all — it adds no row gate, it just lets the RESTRICTIVE delete policy bind.
-- ==========================================================================="""

_COMMANDS = (
    ("select", "SELECT", "USING", False),
    ("insert", "INSERT", "WITH CHECK", True),
    ("update", "UPDATE", "USING-CHECK", True),
    ("delete", "DELETE", "USING", True),
)


def _table_block(table: str, build: PathBuilder) -> str:
    lines = [
        f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
        f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
    ]
    for suffix, command, clause, write in _COMMANDS:
        pred = build(table, write)
        name = f"initiative_member_{suffix}"
        lines.append(f"DROP POLICY IF EXISTS {name} ON {table};")
        lines.append(f"CREATE POLICY {name} ON {table} AS PERMISSIVE FOR {command}")
        if clause == "USING-CHECK":
            lines.append(f"  USING ({pred}) WITH CHECK ({pred});")
        elif clause == "WITH CHECK":
            lines.append(f"  WITH CHECK ({pred});")
        else:  # USING
            lines.append(f"  USING ({pred});")
    if table in _PURGE_GUARD_TABLES:
        # Admin-only hard delete (purge), AND-combined with the PERMISSIVE delete
        # policy above. RESTRICTIVE, so a write-member who clears the permissive
        # leg is still refused unless they are the routed guild admin.
        lines.append("DROP POLICY IF EXISTS soft_delete_admin_purge ON " + table + ";")
        lines.append(
            f"CREATE POLICY soft_delete_admin_purge ON {table} AS RESTRICTIVE FOR DELETE"
        )
        lines.append(f"  USING ({_PURGE_GUARD_PREDICATE});")
    return "\n".join(lines)


def _guild_level_guard_block(table: str) -> str:
    """RLS for a guild-level soft-delete table (initiatives, tags): a permissive
    allow-all (isolation is the schema boundary, not RLS) plus the RESTRICTIVE
    admin-only-purge guard. NOT an access gate — see _GUILD_LEVEL_SECTION."""
    return "\n".join(
        [
            f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
            f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
            f"DROP POLICY IF EXISTS guild_level_open ON {table};",
            f"CREATE POLICY guild_level_open ON {table} AS PERMISSIVE FOR ALL",
            "  USING (true) WITH CHECK (true);",
            f"DROP POLICY IF EXISTS soft_delete_admin_purge ON {table};",
            f"CREATE POLICY soft_delete_admin_purge ON {table} AS RESTRICTIVE FOR DELETE",
            f"  USING ({_PURGE_GUARD_PREDICATE});",
        ]
    )


def generate() -> str:
    blocks = [_table_block(t, INITIATIVE_PATHS[t]) for t in sorted(INITIATIVE_PATHS)]
    out = _HEADER + "\n\n" + "\n\n".join(blocks)
    guards = [_guild_level_guard_block(t) for t in sorted(_GUILD_LEVEL_PURGE_TABLES)]
    if guards:
        out += "\n\n" + _GUILD_LEVEL_SECTION + "\n\n" + "\n\n".join(guards)
    return out + "\n"


if __name__ == "__main__":
    _OUT.write_text(generate())
    n = len(INITIATIVE_PATHS) + len(_GUILD_LEVEL_PURGE_TABLES)
    print(
        f"Wrote {n} table policy blocks "
        f"({len(_GUILD_LEVEL_PURGE_TABLES)} guild-level purge guards) -> {_OUT}"
    )
