"""Generate alembic/guild/guild_rls.sql from the initiative-RLS path registry.

The registry — which tables are initiative-scoped and how each resolves its
initiative — is the single source of truth in ``app.db.initiative_rls``. This
script is just the emitter: it stamps the uniform policy boilerplate (ENABLE /
FORCE RLS + DROP/CREATE × 4 commands, read vs write flag) around each table's
path. Adding an initiative-scoped table means adding a path THERE, then running:

    python scripts/gen_guild_rls.py        # writes alembic/guild/guild_rls.sql

``schema_provisioning.apply_guild_rls`` applies the result to guild_template +
every guild_<id>; ``guild_rls_test.py`` (and a CI step) fail if the committed
file drifts from this generator's output.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow ``python scripts/gen_guild_rls.py`` from backend/ to import the app.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db.initiative_rls import INITIATIVE_PATHS, PathBuilder  # noqa: E402

_OUT = Path(__file__).resolve().parents[1] / "alembic" / "guild" / "guild_rls.sql"

_HEADER = """\
-- AUTOGENERATED by scripts/gen_guild_rls.py — DO NOT EDIT BY HAND.
-- Initiative-member-level RLS for the per-guild CONTENT tables. Schema-relative
-- (run with search_path = <guild_schema>, public). Idempotent.
--
-- The access RULE lives in ONE place, public.initiative_access (initiative member
-- OR guild admin OR PAM, read from the request GUCs); each policy below is just the
-- join that resolves a table's initiative id and defers to it. The per-table paths
-- are the single source of truth in app/db/initiative_rls.py (INITIATIVE_PATHS).
--
-- SCOPE: only INITIATIVE-scoped CONTENT tables are here, exactly
-- app.db.initiative_rls.INITIATIVE_SCOPED_TABLES. The STRUCTURAL initiative tables
-- (initiatives, initiative_members, initiative_roles, initiative_role_permissions)
-- and guild-level / own-row tables (app.db.tenancy.GUILD_LEVEL_TABLES) are NOT
-- initiative-member-scoped: they are guild-scoped by the schema boundary (the
-- membership table can't be gated by the membership check it backs without
-- recursing; own-row scoping would break co-member rosters). The app layer still
-- does finer filtering (e.g. the initiatives list shows member-only for non-admins).
--
-- To add a new initiative-scoped table: add a path to INITIATIVE_PATHS in
-- app/db/initiative_rls.py, then regenerate.
"""

_COMMANDS = (
    ("select", "SELECT", "USING", False),
    ("insert", "INSERT", "WITH CHECK", True),
    ("update", "UPDATE", "USING-CHECK", True),
    ("delete", "DELETE", "USING", True),
)


def _table_block(table: str, build: PathBuilder) -> str:
    lines = [
        f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
        f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
    ]
    for suffix, command, clause, write in _COMMANDS:
        pred = build(table, write)
        name = f"initiative_member_{suffix}"
        lines.append(f"DROP POLICY IF EXISTS {name} ON {table};")
        lines.append(f"CREATE POLICY {name} ON {table} AS PERMISSIVE FOR {command}")
        if clause == "USING-CHECK":
            lines.append(f"  USING ({pred}) WITH CHECK ({pred});")
        elif clause == "WITH CHECK":
            lines.append(f"  WITH CHECK ({pred});")
        else:  # USING
            lines.append(f"  USING ({pred});")
    return "\n".join(lines)


def generate() -> str:
    blocks = [_table_block(t, INITIATIVE_PATHS[t]) for t in sorted(INITIATIVE_PATHS)]
    return _HEADER + "\n\n" + "\n\n".join(blocks) + "\n"


if __name__ == "__main__":
    _OUT.write_text(generate())
    print(f"Wrote {len(INITIATIVE_PATHS)} table policy blocks -> {_OUT}")
