"""Regenerate the app-channel conformance vectors an app-kit is checked against.

The signing material is a published contract: a kit in another language has to
reproduce it byte for byte. These vectors are how that agreement is asserted
rather than assumed — they come out of this build's own implementation, so a
kit's test fails against the platform's answer instead of against a second
reading of the spec.

Written to ``initiative-app-kit``'s ``test/vectors.json``:

    python scripts/gen_channel_vectors.py ../../initiative-app-kit/test/vectors.json

Inputs are fixed here rather than randomized so a regeneration diffs as a change
to the *material*, and to nothing else.
"""

import hashlib
import hmac
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.services.marketplace.app_channel_auth import (  # noqa: E402
    sign_request,
    signing_material,
)

#: Not a secret anywhere. Named so a leak scanner reading the fixture agrees.
SECRET = "test-secret-do-not-use"
CHALLENGE = "9f8e7d6c5b4a39281706"

STAMP = "1765000000"
NONCE = "0123456789abcdef0123456789abcdef"

#: One per shape a caller sends: a body, neither, a path parameter, and a query.
REQUESTS = [
    {
        "method": "POST",
        "path": "/api/v1/app-channel/events",
        "query": "",
        "body": '{"type":"app.acme.tracker.ping"}',
    },
    {
        "method": "GET",
        "path": "/api/v1/app-channel/installs",
        "query": "",
        "body": "",
    },
    {
        "method": "PUT",
        "path": "/api/v1/app-channel/connections/abc",
        "query": "",
        "body": '{"account_label":"@alice"}',
    },
    {
        "method": "GET",
        "path": "/api/v1/app-service/installs/7/connections/resolve",
        "query": "delegate=acme.auto&subject=8Kd2mQ0rXbN4vT7wLpYz1c3F",
        "body": "",
    },
]


def main() -> None:
    vectors = {
        "_note": (
            "Generated by the platform's own app_channel_auth implementation. "
            "Regenerate rather than hand-edit: "
            "backend/scripts/gen_channel_vectors.py"
        ),
        "secret": SECRET,
        "requests": [
            {
                **request,
                "timestamp": STAMP,
                "nonce": NONCE,
                "material": signing_material(
                    method=request["method"],
                    path=request["path"],
                    query=request["query"],
                    timestamp=STAMP,
                    nonce=NONCE,
                    body=request["body"].encode("utf-8"),
                ).decode("utf-8"),
                "signature": sign_request(
                    SECRET,
                    method=request["method"],
                    path=request["path"],
                    query=request["query"],
                    timestamp=STAMP,
                    nonce=NONCE,
                    body=request["body"].encode("utf-8"),
                ),
            }
            for request in REQUESTS
        ],
        "handshake": {
            "challenge": CHALLENGE,
            "response": hmac.new(
                SECRET.encode("utf-8"), CHALLENGE.encode("utf-8"), hashlib.sha256
            ).hexdigest(),
        },
    }

    content = json.dumps(vectors, indent=2) + "\n"
    output = sys.argv[1] if len(sys.argv) > 1 else "-"
    if output == "-":
        print(content, end="")
    else:
        Path(output).write_text(content)
        print(f"wrote {len(REQUESTS)} request vectors to {output}")


if __name__ == "__main__":
    main()
