"""Notifications: who hears about what, and how.

Split by job — :mod:`.delivery` (the one way a notice reaches somebody),
:mod:`.notifiers` (what content changes send), :mod:`.rollup`,
:mod:`.reactions`, :mod:`.digests`, :mod:`.sweeps` (the time-driven
notices) and :mod:`.account_notices`. Callers import from here.
"""

from __future__ import annotations

from app.services.notifications.delivery import (
    AppAuthor,
    Channels,
    MY_TASKS_TARGET_PATH,
    Push,
    actor_name,
    author_of,
    deliver,
    reference_path,
)
from app.services.notifications.rollup import (
    MAX_ROLLED_UP_COMMENTERS,
)
from app.services.notifications.notifiers import (
    notify_comment_mention,
    notify_comment_on_resource,
    notify_comment_on_task,
    notify_comment_reply,
    notify_document_mention,
    notify_event_cancelled,
    notify_event_invitation,
    notify_event_reminder,
    notify_event_rsvp,
    notify_event_updated,
    notify_initiative_join_requested,
    notify_initiative_join_resolved,
    notify_initiative_membership,
    notify_post_published,
    notify_project_added,
    notify_task_description_mention,
    notify_task_mentioned_in_comment,
)
from app.services.notifications.digests import (
    ASSIGNMENT_DIGEST,
    ASSIGNMENT_GC_POLL_SECONDS,
    ASSIGNMENT_ITEM_RETENTION,
    ASSIGNMENT_MAX_WINDOW,
    ASSIGNMENT_QUIET_PERIOD,
    DIGEST_POLL_SECONDS,
    DigestSpec,
    clear_digest_queue_across_guilds,
    clear_digest_queue_for_user,
    dequeue_task_assignment_events,
    enqueue_task_assignment_event,
    process_assignment_digest_gc,
    process_task_assignment_digests,
    wants_assignment_digest,
    wants_digest,
)
from app.services.notifications.reactions import (
    MAX_ROLLED_UP_REACTIONS,
    REACTION_DIGEST,
    enqueue_reaction_event,
    process_reaction_digests,
    withdraw_reaction_event,
)
from app.services.notifications.sweeps import (
    EVENT_REMINDER_GRACE,
    EVENT_REMINDER_POLL_SECONDS,
    HOLD_SUMMARY_POLL_SECONDS,
    OVERDUE_POLL_SECONDS,
    process_event_reminders,
    process_hold_summaries,
    process_overdue_notifications,
)
from app.services.notifications.account_notices import (
    queue_account_suspended,
    queue_account_unsuspended,
    queue_avatar_removed,
    queue_username_changed,
)

__all__ = [
    "ASSIGNMENT_DIGEST",
    "ASSIGNMENT_GC_POLL_SECONDS",
    "ASSIGNMENT_ITEM_RETENTION",
    "ASSIGNMENT_MAX_WINDOW",
    "ASSIGNMENT_QUIET_PERIOD",
    "AppAuthor",
    "Channels",
    "DIGEST_POLL_SECONDS",
    "DigestSpec",
    "EVENT_REMINDER_GRACE",
    "EVENT_REMINDER_POLL_SECONDS",
    "HOLD_SUMMARY_POLL_SECONDS",
    "MAX_ROLLED_UP_COMMENTERS",
    "MAX_ROLLED_UP_REACTIONS",
    "MY_TASKS_TARGET_PATH",
    "OVERDUE_POLL_SECONDS",
    "Push",
    "REACTION_DIGEST",
    "actor_name",
    "author_of",
    "clear_digest_queue_across_guilds",
    "clear_digest_queue_for_user",
    "deliver",
    "dequeue_task_assignment_events",
    "enqueue_reaction_event",
    "enqueue_task_assignment_event",
    "notify_comment_mention",
    "notify_comment_on_resource",
    "notify_comment_on_task",
    "notify_comment_reply",
    "notify_document_mention",
    "notify_event_cancelled",
    "notify_event_invitation",
    "notify_event_reminder",
    "notify_event_rsvp",
    "notify_event_updated",
    "notify_initiative_join_requested",
    "notify_initiative_join_resolved",
    "notify_initiative_membership",
    "notify_post_published",
    "notify_project_added",
    "notify_task_description_mention",
    "notify_task_mentioned_in_comment",
    "process_assignment_digest_gc",
    "process_event_reminders",
    "process_hold_summaries",
    "process_overdue_notifications",
    "process_reaction_digests",
    "process_task_assignment_digests",
    "queue_account_suspended",
    "queue_account_unsuspended",
    "queue_avatar_removed",
    "queue_username_changed",
    "reference_path",
    "wants_assignment_digest",
    "wants_digest",
    "withdraw_reaction_event",
]
