"""Add tool tag junction tables

Guild-content migration: ``queue_tags``, ``counter_group_tags``, and
``advanced_tool_tags`` — one junction per tool that lacked tags, matching the
existing junction shape (composite PK, no ondelete; hard purge cascades via
the Tag ORM relationships). RLS policies come from the ``INITIATIVE_PATHS``
registry at provisioning time, not from this migration.
"""

import sqlalchemy as sa
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260716_0143"
down_revision = "20260715_0142"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advanced_tool_tags",
        sa.Column("advanced_tool_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["advanced_tool_id"],
            ["advanced_tools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("advanced_tool_id", "tag_id"),
    )
    with op.batch_alter_table("advanced_tool_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_advanced_tool_tags_tag_id"), ["tag_id"], unique=False
        )

    op.create_table(
        "counter_group_tags",
        sa.Column("counter_group_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["counter_group_id"],
            ["counter_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("counter_group_id", "tag_id"),
    )
    with op.batch_alter_table("counter_group_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_counter_group_tags_tag_id"), ["tag_id"], unique=False
        )

    op.create_table(
        "queue_tags",
        sa.Column("queue_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("queue_id", "tag_id"),
    )
    with op.batch_alter_table("queue_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_queue_tags_tag_id"), ["tag_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_tags_tag_id"))

    op.drop_table("queue_tags")
    with op.batch_alter_table("counter_group_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_counter_group_tags_tag_id"))

    op.drop_table("counter_group_tags")
    with op.batch_alter_table("advanced_tool_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_advanced_tool_tags_tag_id"))

    op.drop_table("advanced_tool_tags")
    # ### end Alembic commands ###
