"""add dashboards tool

Adds the ``dashboards`` content table (+ its tag junction) and the
``initiatives.dashboards_enabled`` master switch to every guild schema.

Beyond the autogenerated DDL this carries the manual arms a new tool always
needs, because each is guarded by a CHECK or a CASE that would otherwise reject
the new value at runtime:

* ``ck_initiative_role_permissions_permission_key`` — the stored permission-key
  allow-list gains ``dashboards_enabled`` / ``create_dashboards``.
* ``ck_recent_views_entity_type`` — gains ``'dashboard'``.
* ``public.fn_recent_views_set_guild_id`` — gains a ``dashboard`` CASE arm; a
  recentable type with no arm makes every recent-view INSERT fail with
  CaseNotFoundError.

The allow-lists above are written out literally for the same reason RLS is not
applied here: a migration is a historical record, and anything it reads from the
live app describes a LATER state of the world than the revision it runs at.
Deriving the permission keys from ``PermissionKey`` made this migration reject
rows that a later revision had not deleted yet, so every upgrade from an older
database failed while a fresh one passed.

RLS is deliberately NOT applied here, on the same principle: rendering the live
``INITIATIVE_PATHS`` registry mid-history tries to create policies for tables a
subsequent migration has not created yet. Policies (like table grants, which
already work this way) come from provisioning: the registry change bumps the
provisioning stamp, so the boot back-fill applies them to every guild schema.
Until then the new tables carry no grants either, so no role can reach them.
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260811_0162"
down_revision = "20260810_0161"
branch_labels = None
depends_on = None


# Spelled out rather than derived from the tool registry: a migration states the
# shape of the database at its own revision, which must not move when the enums
# do. These are the values as of THIS revision — the advanced-tool keys below
# are still live here and are not removed until 0174, so deriving them from the
# live enum makes 0162 reject rows that 0174 has not deleted yet.
_NEW_PERMISSION_KEYS = [
    "advanced_tools_enabled",
    "calendars_enabled",
    "counter_groups_enabled",
    "create_advanced_tools",
    "create_calendars",
    "create_counter_groups",
    "create_dashboards",
    "create_documents",
    "create_projects",
    "create_queues",
    "dashboards_enabled",
    "documents_enabled",
    "projects_enabled",
    "queues_enabled",
]
_OLD_PERMISSION_KEYS = [
    key
    for key in _NEW_PERMISSION_KEYS
    if key not in ("create_dashboards", "dashboards_enabled")
]

# entity_type -> table the trigger reads guild_id from. Advanced tools were
# never recentable, so they do not appear here.
_NEW_RECENT_TABLES = [
    ("project", "projects"),
    ("document", "documents"),
    ("queue", "queues"),
    ("counter_group", "counter_groups"),
    ("calendar", "calendars"),
    ("dashboard", "dashboards"),
]
_OLD_RECENT_TABLES = [
    (etype, table) for etype, table in _NEW_RECENT_TABLES if etype != "dashboard"
]

_NEW_RECENT_TYPES = [etype for etype, _ in _NEW_RECENT_TABLES]
_OLD_RECENT_TYPES = [etype for etype, _ in _OLD_RECENT_TABLES]


def _swap_permission_key_check(keys: list[str]) -> None:
    values = ", ".join(f"'{key}'" for key in keys)
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "DROP CONSTRAINT IF EXISTS ck_initiative_role_permissions_permission_key"
    )
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "ADD CONSTRAINT ck_initiative_role_permissions_permission_key "
        f"CHECK (permission_key::text = ANY (ARRAY[{values}]::text[]))"
    )


def _swap_recent_check(types: list[str]) -> None:
    values = ", ".join(f"'{value}'::text" for value in types)
    op.execute(
        "ALTER TABLE recent_views DROP CONSTRAINT IF EXISTS ck_recent_views_entity_type"
    )
    op.execute(
        "ALTER TABLE recent_views ADD CONSTRAINT ck_recent_views_entity_type "
        f"CHECK (entity_type = ANY (ARRAY[{values}]))"
    )


def _recent_views_trigger_fn(entity_tables: list[tuple[str, str]]) -> str:
    """Render public.fn_recent_views_set_guild_id with one CASE arm per
    recentable entity type (the trigger denormalizes guild_id from the entity's
    own table; a type with no arm makes every INSERT fail)."""
    arms = "\n".join(
        f"""                    WHEN '{etype}' THEN
                        SELECT guild_id INTO NEW.guild_id FROM {table}
                        WHERE id = NEW.entity_id;"""
        for etype, table in entity_tables
    )
    return f"""
        CREATE OR REPLACE FUNCTION public.fn_recent_views_set_guild_id() RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.guild_id IS NULL OR (TG_OP = 'UPDATE' AND (
                OLD.entity_type IS DISTINCT FROM NEW.entity_type
                OR OLD.entity_id IS DISTINCT FROM NEW.entity_id
            )) THEN
                CASE NEW.entity_type
{arms}
                END CASE;
            END IF;
            RETURN NEW;
        END;
        $$
    """


def upgrade() -> None:
    bind = op.get_bind()
    # The trigger function lives in public and is shared by every guild schema,
    # so it is rewritten once rather than per schema.
    op.execute(_recent_views_trigger_fn(_NEW_RECENT_TABLES))
    run_for_each_guild_schema(bind, _apply_upgrade)


def _apply_upgrade() -> None:
    op.create_table(
        "dashboards",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("initiative_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column("listing_uid", sa.String(length=14), nullable=True),
        sa.Column("listing_version", sa.String(length=32), nullable=True),
        sa.Column(
            "definition",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.id"]),
        sa.ForeignKeyConstraint(
            ["initiative_id"], ["initiatives.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dashboards", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dashboards_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dashboards_initiative_id"), ["initiative_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dashboards_listing_uid"), ["listing_uid"], unique=False
        )

    op.create_table(
        "dashboard_tags",
        sa.Column("dashboard_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.PrimaryKeyConstraint("dashboard_id", "tag_id"),
    )
    with op.batch_alter_table("dashboard_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dashboard_tags_tag_id"), ["tag_id"], unique=False
        )

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "dashboards_enabled",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )

    _swap_permission_key_check(_NEW_PERMISSION_KEYS)
    _swap_recent_check(_NEW_RECENT_TYPES)


def downgrade() -> None:
    bind = op.get_bind()
    run_for_each_guild_schema(bind, _apply_downgrade)
    op.execute(_recent_views_trigger_fn(_OLD_RECENT_TABLES))


def _apply_downgrade() -> None:
    # Drop the rows and the permission keys before the tables they reference.
    op.execute(
        "DELETE FROM initiative_role_permissions WHERE permission_key IN "
        "('dashboards_enabled', 'create_dashboards')"
    )
    _swap_permission_key_check(_OLD_PERMISSION_KEYS)
    op.execute("DELETE FROM recent_views WHERE entity_type = 'dashboard'")
    _swap_recent_check(_OLD_RECENT_TYPES)
    op.execute("DELETE FROM resource_grants WHERE resource_type = 'dashboard'")

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.drop_column("dashboards_enabled")

    with op.batch_alter_table("dashboard_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboard_tags_tag_id"))
    op.drop_table("dashboard_tags")

    with op.batch_alter_table("dashboards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboards_listing_uid"))
        batch_op.drop_index(batch_op.f("ix_dashboards_initiative_id"))
        batch_op.drop_index(batch_op.f("ix_dashboards_guild_id"))
    op.drop_table("dashboards")
