"""add task_assignees.completed_at

Completion is per assignment, not per task: someone can be done with their share
while the task itself is still in review or waiting on a co-assignee. The task's
status keeps recording where the work as a whole stands.

No backfill. Assignments on tasks already sitting in a done column are left
unstamped rather than credited to the migration's clock — an invented
completion time would be indistinguishable from a real one, and the only
consumer (the focus list) shows a rolling day of finished work, where a wrong
timestamp is worse than an absent one. They stamp themselves the next time the
task's status moves.
"""

import sqlalchemy as sa
from alembic import op
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260810_0160"
down_revision = "20260806_0159"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    with op.batch_alter_table("task_assignees", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
        )


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    with op.batch_alter_table("task_assignees", schema=None) as batch_op:
        batch_op.drop_column("completed_at")
