"""add posts tool

The bulletin board: one ``posts`` table per guild schema, its tag junction, the
comment parent that lets a notice carry a thread, and the initiative master
switch.

Four CHECK constraints carry a vocabulary that just grew, and each is
rewritten rather than extended because Postgres has no "add a value" for one:
the comment single-parent rule, the initiative permission keys, the reaction
target kinds, and the recent-view entity types. Their values are written out
literally here rather than derived from the enums — a migration records what
was true at this revision, and a later enum change must be a later migration.

``public.fn_recent_views_set_guild_id`` gains a ``post`` arm for the same
reason, and is the one that bites hardest if forgotten: it is a **plpgsql**
CASE, which RAISES when nothing matches, where the SQL CASE beside it would
merely be NULL. A recentable type with no arm makes every view of it fail with
``CaseNotFoundError``. The function lives in ``public`` and is shared by every
guild schema, so it is replaced once rather than per schema. It also gains an
``ELSE`` that names the offending type, so the next omission says what is wrong
instead of "CASE statement is missing ELSE part" from inside an INSERT.

RLS policies, table grants and the ``created_by`` trigger are NOT written
here: provisioning renders those from the live ``guild_template`` and the
registries, and the boot backfill re-applies them to every guild whose stamp
this revision made stale.

Revision ID: 20260905_0228
Revises: 20260905_0227
Create Date: 2026-09-05
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260905_0228"
down_revision = "20260905_0227"
branch_labels = None
depends_on = None


# Every comment parent after this revision — the task plus one column per tool.
_PARENTS_AFTER = (
    "task_id",
    "document_id",
    "project_id",
    "queue_id",
    "counter_group_id",
    "calendar_id",
    "dashboard_id",
    "post_id",
)
_PARENTS_BEFORE = _PARENTS_AFTER[:-1]

_PERMISSION_KEYS_AFTER = (
    "calendars_enabled",
    "counter_groups_enabled",
    "create_calendars",
    "create_counter_groups",
    "create_dashboards",
    "create_documents",
    "create_posts",
    "create_projects",
    "create_queues",
    "dashboards_enabled",
    "documents_enabled",
    "posts_enabled",
    "projects_enabled",
    "queues_enabled",
)
_PERMISSION_KEYS_BEFORE = tuple(
    key
    for key in _PERMISSION_KEYS_AFTER
    if key not in ("create_posts", "posts_enabled")
)

_REACTION_TARGETS_AFTER = ("comment", "post")
_REACTION_TARGETS_BEFORE = ("comment",)

#: (entity_type, table) for every recentable tool, in the order the function
#: has always listed them. The CHECK vocabulary below is the same set, sorted.
_RECENT_TABLES_AFTER = (
    ("project", "projects"),
    ("document", "documents"),
    ("queue", "queues"),
    ("counter_group", "counter_groups"),
    ("calendar", "calendars"),
    ("dashboard", "dashboards"),
    ("post", "posts"),
)
_RECENT_TABLES_BEFORE = _RECENT_TABLES_AFTER[:-1]

_RECENT_TYPES_AFTER = tuple(sorted(etype for etype, _ in _RECENT_TABLES_AFTER))
_RECENT_TYPES_BEFORE = tuple(t for t in _RECENT_TYPES_AFTER if t != "post")

#: Asks the next boot to rebuild this guild's search triggers and re-sweep its
#: entries through the registry — which is how ``posts`` starts being indexed.
_CLEAR_SEARCH_GENERATION = "COMMENT ON TABLE search_entries IS NULL"


def _quoted(values) -> str:
    return ", ".join(f"'{value}'" for value in values)


def _single_parent_check(columns) -> str:
    return f"num_nonnulls({', '.join(columns)}) = 1"


def _swap_comment_parent_check(columns) -> None:
    op.execute(
        "ALTER TABLE comments DROP CONSTRAINT IF EXISTS ck_comments_single_parent"
    )
    op.create_check_constraint(
        "ck_comments_single_parent", "comments", _single_parent_check(columns)
    )


def _swap_permission_key_check(keys) -> None:
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "DROP CONSTRAINT IF EXISTS ck_initiative_role_permissions_permission_key"
    )
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "ADD CONSTRAINT ck_initiative_role_permissions_permission_key "
        f"CHECK (permission_key::text = ANY (ARRAY[{_quoted(keys)}]::text[]))"
    )


def _swap_reaction_target_check(targets) -> None:
    op.execute(
        "ALTER TABLE reactions DROP CONSTRAINT IF EXISTS ck_reactions_target_type"
    )
    op.execute(
        "ALTER TABLE reactions ADD CONSTRAINT ck_reactions_target_type "
        f"CHECK (target_type IN ({_quoted(targets)}))"
    )


def _recent_views_trigger_fn(entity_tables, *, with_else: bool) -> str:
    """``public.fn_recent_views_set_guild_id`` with one CASE arm per recentable
    entity type — the trigger denormalizes ``guild_id`` from the entity's own
    table, and a type with no arm makes every INSERT for it fail."""
    arms = "\n".join(
        f"""                    WHEN '{etype}' THEN
                        SELECT guild_id INTO NEW.guild_id FROM {table}
                        WHERE id = NEW.entity_id;"""
        for etype, table in entity_tables
    )
    fallback = (
        """
                    ELSE
                        RAISE EXCEPTION
                            'fn_recent_views_set_guild_id has no arm for entity_type %',
                            NEW.entity_type;"""
        if with_else
        else ""
    )
    return f"""
        CREATE OR REPLACE FUNCTION public.fn_recent_views_set_guild_id() RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.guild_id IS NULL OR (TG_OP = 'UPDATE' AND (
                OLD.entity_type IS DISTINCT FROM NEW.entity_type
                OR OLD.entity_id IS DISTINCT FROM NEW.entity_id
            )) THEN
                CASE NEW.entity_type
{arms}{fallback}
                END CASE;
            END IF;
            RETURN NEW;
        END;
        $$
    """


def _swap_recent_check(types) -> None:
    op.execute(
        "ALTER TABLE recent_views DROP CONSTRAINT IF EXISTS ck_recent_views_entity_type"
    )
    op.execute(
        "ALTER TABLE recent_views ADD CONSTRAINT ck_recent_views_entity_type "
        f"CHECK (entity_type = ANY (ARRAY[{_quoted(types)}]))"
    )


def upgrade() -> None:
    # Shared by every guild schema, so it is rewritten once.
    op.execute(_recent_views_trigger_fn(_RECENT_TABLES_AFTER, with_else=True))
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    op.create_table(
        "posts",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "comments_disabled",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("initiative_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "body",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_by", sa.Integer(), nullable=True),
        sa.Column("pin_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiative_id"], ["initiatives.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_posts_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_posts_initiative_id"), ["initiative_id"], unique=False
        )
        # The board reads the pinned band first on every page.
        batch_op.create_index(
            batch_op.f("ix_posts_pinned_at"), ["pinned_at"], unique=False
        )

    op.create_table(
        "post_tags",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "tag_id"),
    )
    with op.batch_alter_table("post_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_tags_tag_id"), ["tag_id"], unique=False
        )

    # The comment parent. Its FK cascades so deleting a post takes its thread
    # with it, matching every other tool parent.
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "comments_post_id_fkey",
        "comments",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_comments_post_id", "comments", ["post_id"])
    _swap_comment_parent_check(_PARENTS_AFTER)

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "posts_enabled",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )

    _swap_permission_key_check(_PERMISSION_KEYS_AFTER)
    _swap_reaction_target_check(_REACTION_TARGETS_AFTER)
    _swap_recent_check(_RECENT_TYPES_AFTER)
    op.execute(_CLEAR_SEARCH_GENERATION)


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)
    op.execute(_recent_views_trigger_fn(_RECENT_TABLES_BEFORE, with_else=False))


#: Tables the downgrade has to clear post rows out of. Each carries FORCE ROW
#: LEVEL SECURITY, which binds the table's owner — the role a migration runs as
#: — and the policies key on request GUCs a migration has no value for. Without
#: lifting it the DELETEs below match nothing and the CHECK narrowing that
#: follows fails on the rows they were meant to remove.
_CLEANUP_TABLES = (
    "comments",
    "reactions",
    "recent_views",
    "search_entries",
    "initiative_role_permissions",
)


#: Drops every rendered policy that mentions a post, wherever it lives.
#:
#: The initiative-member policies reach a post directly (``recent_views``), or
#: through ``comments.post_id`` (``reactions`` and the comment tables), and
#: Postgres will not drop a table or column a policy depends on. Discovered
#: from the catalog rather than listed, because a list is the thing that drifts
#: — which is how this migration shipped without its trigger arm.
#:
#: The next boot undoes it: the provisioning stamp no longer matches, so the
#: backfill re-renders every policy from the registry. Until then those tables
#: are deny-all, which is the right way for a half-applied downgrade to fail.
_DROP_POST_POLICIES = """
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT c.relname, p.polname
        FROM pg_policy p
        JOIN pg_class c ON c.oid = p.polrelid
        WHERE c.relnamespace = current_schema()::regnamespace
          AND (coalesce(pg_get_expr(p.polqual, p.polrelid), '') LIKE '%posts%'
               OR coalesce(pg_get_expr(p.polqual, p.polrelid), '') LIKE '%post_id%'
               OR coalesce(pg_get_expr(p.polwithcheck, p.polrelid), '') LIKE '%posts%'
               OR coalesce(pg_get_expr(p.polwithcheck, p.polrelid), '') LIKE '%post_id%')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', r.polname, r.relname);
    END LOOP;
END $$;
"""


def _apply_downgrade() -> None:
    op.execute(_DROP_POST_POLICIES)

    # Rows that name a post have no place in the narrower vocabularies, and a
    # CHECK cannot be narrowed around them.
    for table in _CLEANUP_TABLES:
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
    try:
        op.execute("DELETE FROM comments WHERE post_id IS NOT NULL")
        op.execute("DELETE FROM reactions WHERE target_type = 'post'")
        op.execute("DELETE FROM recent_views WHERE entity_type = 'post'")
        op.execute("DELETE FROM search_entries WHERE entity_type = 'post'")
        op.execute(
            "DELETE FROM initiative_role_permissions WHERE permission_key IN "
            "('create_posts', 'posts_enabled')"
        )
    finally:
        for table in _CLEANUP_TABLES:
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

    _swap_recent_check(_RECENT_TYPES_BEFORE)
    _swap_reaction_target_check(_REACTION_TARGETS_BEFORE)
    _swap_permission_key_check(_PERMISSION_KEYS_BEFORE)

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.drop_column("posts_enabled")

    _swap_comment_parent_check(_PARENTS_BEFORE)
    op.drop_index("ix_comments_post_id", table_name="comments")
    op.drop_constraint("comments_post_id_fkey", "comments", type_="foreignkey")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_column("post_id")

    with op.batch_alter_table("post_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_tags_tag_id"))
    op.drop_table("post_tags")

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_pinned_at"))
        batch_op.drop_index(batch_op.f("ix_posts_initiative_id"))
        batch_op.drop_index(batch_op.f("ix_posts_guild_id"))
    op.drop_table("posts")

    # Same as the upgrade: the next boot rebuilds triggers and re-sweeps, which
    # is what takes the post entries' triggers back out.
    op.execute(_CLEAR_SEARCH_GENERATION)
