"""add post polls

Three tables for the question a notice can ask.

``post_polls`` is one-to-one with ``posts`` — the unique key on ``post_id`` is
what says a notice asks at most one question — and carries the settings that
decide how it is answered and how much of the answer each reader sees.

``post_poll_options`` holds the choices in the order they were written. Its
unique key on ``(poll_id, id)`` is redundant against its own primary key and
exists for one reason: it lets a vote carry a foreign key spanning BOTH
columns, so the database guarantees a ballot's ``poll_id`` names the same poll
its option belongs to. The service never has to check.

``post_poll_votes`` is one row per person per choice, keyed on
``(option_id, user_id)`` — a multiple-choice poll is several rows for one
voter, and the "only one" rule of a single-choice poll is the service's,
applied by clearing the voter's rows before writing new ones. No FK to
``users``: that table lives in ``public`` and this one is per-guild.

Deletion cascades the whole way down, so removing a poll takes its choices and
their ballots, and removing a notice takes its poll.

RLS is not applied here. All three are registered in ``INITIATIVE_PATHS``, so
provisioning renders their policies from the registry and the boot backfill
applies them to every guild schema — the registry edit is what bumps the stamp.

Revision ID: 20260906_0232
Revises: 20260906_0231
Create Date: 2026-09-06
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260906_0232"
down_revision = "20260906_0231"
branch_labels = None
depends_on = None

#: Who made a row is filled by the database, from the request GUC the session
#: already sets for RLS — the same shape every other guild-content table uses.
_CREATED_BY_TABLES = ("post_polls", "post_poll_options")


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_polls",
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column(
            "question", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "allows_multiple",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_anonymous",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "hide_results",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", name="uq_post_polls_post_id"),
    )
    with op.batch_alter_table("post_polls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_polls_post_id"), ["post_id"], unique=False
        )

    op.create_table(
        "post_poll_options",
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("poll_id", sa.Integer(), nullable=False),
        sa.Column(
            "position", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["poll_id"], ["post_polls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("poll_id", "id", name="uq_post_poll_options_poll_id_id"),
    )
    with op.batch_alter_table("post_poll_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_poll_options_poll_id"), ["poll_id"], unique=False
        )

    op.create_table(
        "post_poll_votes",
        sa.Column("poll_id", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id", "option_id"],
            ["post_poll_options.poll_id", "post_poll_options.id"],
            name="fk_post_poll_votes_option",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("option_id", "user_id"),
    )
    with op.batch_alter_table("post_poll_votes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_poll_votes_poll_id"), ["poll_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_post_poll_votes_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("search_entries", schema=None) as batch_op:
        batch_op.drop_table_comment(existing_comment="search:819aa052d97dc7fb")

    # ### end Alembic commands ###

    for table in _CREATED_BY_TABLES:
        op.execute(
            f"CREATE OR REPLACE TRIGGER tr_{table}_set_created_by "
            f"BEFORE INSERT ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION public.fn_set_created_by()"
        )


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_entries", schema=None) as batch_op:
        batch_op.create_table_comment("search:819aa052d97dc7fb", existing_comment=None)

    with op.batch_alter_table("post_poll_votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_poll_votes_user_id"))
        batch_op.drop_index(batch_op.f("ix_post_poll_votes_poll_id"))

    op.drop_table("post_poll_votes")
    with op.batch_alter_table("post_poll_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_poll_options_poll_id"))

    op.drop_table("post_poll_options")
    with op.batch_alter_table("post_polls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_polls_post_id"))

    op.drop_table("post_polls")
    # ### end Alembic commands ###
