"""add project filter presets

Presets are seeded rows, not code-defined built-ins, so every project that
already exists gets the same four ("All", "Incomplete", "Unassigned", "Mine")
here. "All" is the default, which is what the project already behaved like, so
the backfill is a no-op from a user's point of view.

Note "Incomplete" filters on status *categories*, never status ids: ids are
per-project rows, so an id-based preset would not survive being shared,
duplicated, or copied from a template.
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260826_0195"
down_revision = "20260825_0194"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_filter_presets",
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "slug", name="uq_project_filter_presets_slug"
        ),
    )
    with op.batch_alter_table("project_filter_presets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_filter_presets_one_default",
            ["project_id"],
            unique=True,
            postgresql_where=sa.text("is_default"),
        )
        batch_op.create_index(
            batch_op.f("ix_project_filter_presets_project_id"),
            ["project_id"],
            unique=False,
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_view_mode", sa.String(length=16), nullable=True)
        )

    # ### end Alembic commands ###

    _attach_triggers()
    _seed_default_presets()


# guild_id is denormalized onto every guild-content row and filled by a BEFORE
# trigger rather than by the app, the same shape task_statuses uses: the
# function is shared (public, unqualified parent read) so under
# search_path=<guild_schema>,public it resolves that guild's own projects.
# created_by is filled the same way, from the request GUC.
_GUILD_ID_FUNCTION = """
CREATE OR REPLACE FUNCTION public.fn_project_filter_presets_set_guild_id()
    RETURNS trigger LANGUAGE plpgsql AS $guild$
BEGIN
    IF NEW.guild_id IS NULL
       OR (TG_OP = 'UPDATE' AND OLD.project_id IS DISTINCT FROM NEW.project_id) THEN
        SELECT guild_id INTO NEW.guild_id FROM projects WHERE id = NEW.project_id;
    END IF;
    RETURN NEW;
END;
$guild$;
"""


def _attach_triggers() -> None:
    # Idempotent: the function is CREATE OR REPLACE and lives once in public,
    # so re-running the per-schema loop just re-asserts it.
    op.execute(_GUILD_ID_FUNCTION)
    op.execute(
        "CREATE OR REPLACE TRIGGER tr_project_filter_presets_set_guild_id "
        "BEFORE INSERT OR UPDATE OF project_id ON project_filter_presets "
        "FOR EACH ROW EXECUTE FUNCTION public.fn_project_filter_presets_set_guild_id()"
    )
    op.execute(
        "CREATE OR REPLACE TRIGGER tr_project_filter_presets_set_created_by "
        "BEFORE INSERT ON project_filter_presets "
        "FOR EACH ROW EXECUTE FUNCTION public.fn_set_created_by()"
    )


# The same four the service seeds for new projects
# (app/services/tenant/filter_presets.DEFAULT_FILTER_PRESETS). Held here as
# literal SQL rather than imported: a migration is a record of what ran, and
# must keep meaning the same after that constant is next edited.
_DEFAULT_PRESETS_SQL = """
INSERT INTO project_filter_presets
    (guild_id, project_id, slug, name, position, is_default, filters,
     created_at, updated_at)
SELECT p.guild_id, p.id, d.slug, d.name, d.position, d.is_default,
       d.filters::jsonb, now(), now()
FROM projects p
CROSS JOIN (VALUES
    ('all',        'All',        0, true,  '{}'),
    ('incomplete', 'Incomplete', 1, false,
     '{"status_categories":["backlog","todo","in_progress"]}'),
    ('unassigned', 'Unassigned', 2, false, '{"assignees":["none"]}'),
    ('mine',       'Mine',       3, false, '{"assignees":["me"]}')
) AS d(slug, name, position, is_default, filters)
WHERE NOT EXISTS (
    SELECT 1 FROM project_filter_presets x WHERE x.project_id = p.id
)
"""


def _seed_default_presets() -> None:
    op.execute(sa.text(_DEFAULT_PRESETS_SQL))


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("default_view_mode")

    with op.batch_alter_table("project_filter_presets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_filter_presets_project_id"))
        batch_op.drop_index(
            "ix_project_filter_presets_one_default",
            postgresql_where=sa.text("is_default"),
        )

    op.drop_table("project_filter_presets")
    # ### end Alembic commands ###
    op.execute(
        "DROP FUNCTION IF EXISTS public.fn_project_filter_presets_set_guild_id()"
    )
