"""guild scope: initiative_access NULL branch, nullable calendar + grant initiative

Gives ``initiative_id IS NULL`` a meaning: **guild-level scope**. A row that
belongs to no initiative belongs to the guild.

``public.initiative_access`` gains an explicit NULL branch. Until now a NULL
simply failed the membership check, so such a row was reachable only by the
guild-admin and PAM legs — an artefact of how the check evaluated rather than a
decision. It now passes for any session routed into the guild schema, because
the initiative gate has nothing to say about a row that belongs to no
initiative. The guild schema boundary still applies (a session reaches only its
own guild's rows), the sign-in policy gate still applies (it AND-wraps every
leg), and a PAM session is still bounded by the privileges of the role it is
routed as. Which *members* may read or write a guild-level row is decided by its
``resource_grants``, exactly as it is for initiative content.

``calendars.initiative_id`` and ``resource_grants.initiative_id`` become
nullable so a calendar can be guild-level and so grants can be written against
guild-level resources at all.

Today the only table with NULL rows is ``advanced_tools``, whose guild-wide rows
were consequently admin-only; they become grant-governed like everything else.
Creating one remains admin-gated at the endpoint, and the list endpoint already
narrows to granted rows for ordinary members, so a guild-wide tool with no
grants stays unlisted for them.
"""

import sqlalchemy as sa
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260812_0165"
down_revision = "20260812_0164"
branch_labels = None
depends_on = None


#: The access rule, with the guild-level branch. Everything else is unchanged
#: from the prior definition (20260718_0147).
INITIATIVE_ACCESS_FN = """
CREATE OR REPLACE FUNCTION public.initiative_access(
    p_initiative_id integer, p_user_id integer, p_need_write boolean DEFAULT false
) RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
    SELECT
        public.guild_auth_satisfied()
        AND (
            -- Guild-level scope: the row belongs to no initiative, so the
            -- initiative gate has nothing to decide. The schema boundary still
            -- confines it to this guild; grants decide who may read or write it.
            p_initiative_id IS NULL
            OR current_setting('app.current_guild_role'::text, true) = 'admin'::text
            OR (CASE
                  WHEN p_need_write
                    THEN current_setting('app.pam_write'::text, true) = 'true'::text
                  ELSE current_setting('app.pam_read'::text, true) = 'true'::text
                       OR current_setting('app.pam_write'::text, true) = 'true'::text
                END)
            OR EXISTS (
                SELECT 1 FROM initiative_members im
                WHERE im.initiative_id = p_initiative_id
                  AND im.user_id = p_user_id
            )
        )
$$;
"""

#: The definition this replaces, restored on downgrade.
INITIATIVE_ACCESS_FN_PRIOR = """
CREATE OR REPLACE FUNCTION public.initiative_access(
    p_initiative_id integer, p_user_id integer, p_need_write boolean DEFAULT false
) RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
    SELECT
        public.guild_auth_satisfied()
        AND (
            current_setting('app.current_guild_role'::text, true) = 'admin'::text
            OR (CASE
                  WHEN p_need_write
                    THEN current_setting('app.pam_write'::text, true) = 'true'::text
                  ELSE current_setting('app.pam_read'::text, true) = 'true'::text
                       OR current_setting('app.pam_write'::text, true) = 'true'::text
                END)
            OR EXISTS (
                SELECT 1 FROM initiative_members im
                WHERE im.initiative_id = p_initiative_id
                  AND im.user_id = p_user_id
            )
        )
$$;
"""


def upgrade() -> None:
    # public, applied once — the per-schema loop below is for the guild tables.
    # The body names `initiative_members` unqualified because it resolves per
    # call through the routed search_path; at migration time no guild schema is
    # on the path, so body validation is deferred (as in 20260718_0147).
    op.execute("SET LOCAL check_function_bodies = false")
    op.execute(INITIATIVE_ACCESS_FN)
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.alter_column(
            "initiative_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("resource_grants", schema=None) as batch_op:
        batch_op.alter_column(
            "initiative_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)
    op.execute("SET LOCAL check_function_bodies = false")
    op.execute(INITIATIVE_ACCESS_FN_PRIOR)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_grants", schema=None) as batch_op:
        batch_op.alter_column(
            "initiative_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.alter_column(
            "initiative_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
