"""calendar container tool

The events tool becomes a Calendar container tool (``Tool.calendar``): a new
``calendars`` table is the shareable DAC anchor and events hang off it via
``calendar_id`` — the same shape as projects → tasks.

Guild-content migration, per schema (``guild_template`` + every ``guild_<id>``):

- create ``calendars`` + ``calendar_tags``;
- backfill one renamable "Default Calendar" per initiative that has events
  (creator = the initiative's earliest event author) and point its events at it;
- seed the default calendar's grants — every ``is_manager`` initiative role at
  ``owner`` plus an all-initiative-members ``read`` row — and drop the old
  per-event ``calendar_event`` grants (sharing is per calendar now);
- swap ``calendar_events.initiative_id`` for NOT NULL ``calendar_id``;
- rename the initiative master switch ``calendar_events_enabled`` →
  ``calendars_enabled`` and the stored permission keys to the new
  ``PermissionKey`` spellings;
- recents: ``calendar`` replaces ``calendar_event`` (events, like tasks, are no
  longer recentable) in the CHECK constraint, the shared trigger function, and
  the stored rows.

RLS policies are re-applied per schema as the final upgrade step by running the
registry-rendered DDL (``render_guild_rls_ddl``) — the same idempotent script
provisioning/boot backfill re-asserts — because ``guild_template`` is not a
provisioning target (the boot backfill enumerates real guilds only) and the
event-table policies must be dropped mid-migration to release the swapped
column. The downgrade does NOT re-render (the running registry describes the
new shape); restored tables stay fail-closed until the deployed code's boot
backfill re-applies its policies. DML here runs as the table owner with
``NO FORCE ROW LEVEL SECURITY`` toggled around it (FORCE would leave the owner
policy-bound and silently skip rows), and the event backfill asserts a zero
orphan count per schema.

Pre-v1 breaking rename — no compatibility shims. Downgrade restores the old
structure; per-event grants are reconstituted as creator-owner +
all-initiative-members read (the pre-migration per-event sharing detail is not
recoverable).
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_ddl import render_guild_rls_ddl
from app.db.guild_migrations import run_for_each_guild_schema, split_sql_statements

revision = "20260804_0157"
down_revision = "20260803_0156"
branch_labels = None
depends_on = None


_OLD_PERMISSION_KEYS = [
    "documents_enabled",
    "projects_enabled",
    "create_documents",
    "create_projects",
    "queues_enabled",
    "create_queues",
    "calendar_events_enabled",
    "create_calendar_events",
    "advanced_tools_enabled",
    "create_advanced_tools",
    "counter_groups_enabled",
    "create_counter_groups",
]

_PERMISSION_KEY_RENAMES = [
    ("calendar_events_enabled", "calendars_enabled"),
    ("create_calendar_events", "create_calendars"),
]

_NEW_PERMISSION_KEYS = [
    dict(_PERMISSION_KEY_RENAMES).get(key, key) for key in _OLD_PERMISSION_KEYS
]

_OLD_RECENT_TYPES = (
    "'project'::text, 'document'::text, 'queue'::text, 'counter_group'::text, "
    "'calendar_event'::text"
)
_NEW_RECENT_TYPES = (
    "'project'::text, 'document'::text, 'queue'::text, 'counter_group'::text, "
    "'calendar'::text"
)

_OLD_ENTITY_TABLES = [
    ("project", "projects"),
    ("document", "documents"),
    ("queue", "queues"),
    ("counter_group", "counter_groups"),
    ("calendar_event", "calendar_events"),
]
_NEW_ENTITY_TABLES = [
    ("project", "projects"),
    ("document", "documents"),
    ("queue", "queues"),
    ("counter_group", "counter_groups"),
    ("calendar", "calendars"),
]


def _rewrite_permission_keys(renames: list[tuple[str, str]]) -> None:
    cases = " ".join(
        f"WHEN permission_key = '{old}' THEN '{new}'" for old, new in renames
    )
    olds = ", ".join(f"'{old}'" for old, _new in renames)
    op.execute(
        f"UPDATE initiative_role_permissions "
        f"SET permission_key = CASE {cases} ELSE permission_key END "
        f"WHERE permission_key IN ({olds})"
    )


def _swap_permission_key_check(keys: list[str]) -> None:
    values = ", ".join(f"'{key}'" for key in keys)
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "DROP CONSTRAINT IF EXISTS ck_initiative_role_permissions_permission_key"
    )
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "ADD CONSTRAINT ck_initiative_role_permissions_permission_key "
        f"CHECK (permission_key::text = ANY (ARRAY[{values}]::text[]))"
    )


def _swap_recent_check(types: str) -> None:
    op.execute(
        "ALTER TABLE recent_views DROP CONSTRAINT IF EXISTS ck_recent_views_entity_type"
    )
    op.execute(
        "ALTER TABLE recent_views ADD CONSTRAINT ck_recent_views_entity_type "
        f"CHECK (entity_type = ANY (ARRAY[{types}]))"
    )


def _recent_views_trigger_fn(entity_tables: list[tuple[str, str]]) -> str:
    """Render public.fn_recent_views_set_guild_id with one CASE arm per
    recentable entity type (the trigger denormalizes guild_id from the entity's
    own table; a type with no arm makes every INSERT fail with
    CaseNotFoundError)."""
    arms = "\n".join(
        f"""                    WHEN '{etype}' THEN
                        SELECT guild_id INTO NEW.guild_id FROM {table}
                        WHERE id = NEW.entity_id;"""
        for etype, table in entity_tables
    )
    return f"""
        CREATE OR REPLACE FUNCTION public.fn_recent_views_set_guild_id() RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.guild_id IS NULL OR (TG_OP = 'UPDATE' AND (
                OLD.entity_type IS DISTINCT FROM NEW.entity_type
                OR OLD.entity_id IS DISTINCT FROM NEW.entity_id
            )) THEN
                CASE NEW.entity_type
{arms}
                END CASE;
            END IF;
            RETURN NEW;
        END;
        $$
    """


# Tables whose rows this migration mutates and that carry FORCE RLS (which
# binds even the owning role). Toggled to NO FORCE around the DML and restored
# right after, per table, inside the same transaction.
_FORCE_RLS_DML_TABLES = ("calendar_events", "resource_grants", "recent_views")

# Tables whose registry-rendered initiative_member_* policies reference the
# column being swapped (initiative_id upgrade / calendar_id downgrade) — the
# column drop is blocked until the policies go. They are re-rendered from
# INITIATIVE_PATHS by the provisioning stamp backfill on next boot; in between,
# RLS stays enabled with no permissive policies (fail closed).
_EVENT_POLICY_TABLES = (
    "calendar_events",
    "calendar_event_attendees",
    "calendar_event_documents",
    "calendar_event_property_values",
    "calendar_event_tags",
    "event_reminder_dispatches",
)


def _drop_initiative_member_policies(tables: tuple[str, ...]) -> None:
    for table in tables:
        for suffix in ("select", "insert", "update", "delete"):
            op.execute(f"DROP POLICY IF EXISTS initiative_member_{suffix} ON {table}")


def _without_force_rls(tables: tuple[str, ...]):
    class _Guard:
        def __enter__(self):
            for table in tables:
                op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")

        def __exit__(self, exc_type, exc, tb):
            for table in tables:
                op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            return False

    return _Guard()


def upgrade() -> None:
    # Shared public-schema trigger function: one replacement, not per guild.
    op.execute(_recent_views_trigger_fn(_NEW_ENTITY_TABLES))
    # Rendered once; schema-relative, so the per-schema search_path routes it.
    rls_statements = split_sql_statements(render_guild_rls_ddl())
    run_for_each_guild_schema(op.get_bind(), lambda: _apply_upgrade(rls_statements))


def _apply_upgrade(rls_statements: list[str]) -> None:
    # 1. New tables (table grants still arrive via the provisioning stamp
    #    backfill on next boot, like 0127/0143; RLS lands in step 8 below).
    op.create_table(
        "calendars",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("initiative_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.id"]),
        sa.ForeignKeyConstraint(["initiative_id"], ["initiatives.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendars_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_calendars_initiative_id"), ["initiative_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_calendars_name"), ["name"], unique=False)

    op.create_table(
        "calendar_tags",
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendars.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.PrimaryKeyConstraint("calendar_id", "tag_id"),
    )
    with op.batch_alter_table("calendar_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendar_tags_tag_id"), ["tag_id"], unique=False
        )

    # 2. Events point at their calendar (nullable during the backfill).
    op.add_column(
        "calendar_events", sa.Column("calendar_id", sa.Integer(), nullable=True)
    )

    with _without_force_rls(_FORCE_RLS_DML_TABLES):
        # 3. One default calendar per initiative that has events (soft-deleted
        #    included — they must restore into a live calendar). Creator = the
        #    initiative's earliest event author.
        op.execute(
            """
            INSERT INTO calendars (
                guild_id, initiative_id, name, created_by_id, created_at, updated_at
            )
            SELECT DISTINCT ON (ce.initiative_id)
                ce.guild_id,
                ce.initiative_id,
                'Default Calendar',
                first_event.created_by_id,
                now(),
                now()
            FROM calendar_events ce
            CROSS JOIN LATERAL (
                SELECT ce2.created_by_id
                FROM calendar_events ce2
                WHERE ce2.initiative_id = ce.initiative_id
                ORDER BY ce2.created_at ASC, ce2.id ASC
                LIMIT 1
            ) AS first_event
            """
        )
        op.execute(
            """
            UPDATE calendar_events
            SET calendar_id = c.id
            FROM calendars c
            WHERE c.initiative_id = calendar_events.initiative_id
            """
        )
        # Fail loudly on any event the backfill missed — a NULL calendar_id row
        # would be silently dropped by the NOT NULL step below otherwise.
        orphans = (
            op.get_bind()
            .execute(
                sa.text(
                    "SELECT count(*) FROM calendar_events WHERE calendar_id IS NULL"
                )
            )
            .scalar()
        )
        if orphans:
            raise RuntimeError(
                f"calendar backfill left {orphans} calendar_events without a calendar"
            )

        # 4. Default-calendar sharing: manager roles own it, every initiative
        #    member reads it. Per-event grants are gone — sharing is per
        #    calendar now.
        op.execute(
            """
            INSERT INTO resource_grants (
                guild_id, initiative_id, resource_type, resource_id,
                user_id, role_id, level, created_at, all_initiative_members
            )
            SELECT c.guild_id, c.initiative_id, 'calendar', c.id,
                   NULL, r.id, 'owner', now(), false
            FROM calendars c
            JOIN initiative_roles r
              ON r.initiative_id = c.initiative_id AND r.is_manager
            """
        )
        op.execute(
            """
            INSERT INTO resource_grants (
                guild_id, initiative_id, resource_type, resource_id,
                user_id, role_id, level, created_at, all_initiative_members
            )
            SELECT c.guild_id, c.initiative_id, 'calendar', c.id,
                   NULL, NULL, 'read', now(), true
            FROM calendars c
            """
        )
        op.execute("DELETE FROM resource_grants WHERE resource_type = 'calendar_event'")

        # 7. Events (like tasks) are no longer recentable; calendars are.
        op.execute("DELETE FROM recent_views WHERE entity_type = 'calendar_event'")

    # 5. Swap the anchor column: calendar_id becomes the identity, the direct
    #    initiative_id goes away (initiative derives via the calendar). The old
    #    policies read initiative_id and must go first.
    _drop_initiative_member_policies(_EVENT_POLICY_TABLES)
    op.alter_column("calendar_events", "calendar_id", nullable=False)
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendar_events_calendar_id"), ["calendar_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("calendar_events_calendar_id_fkey"),
            "calendars",
            ["calendar_id"],
            ["id"],
        )
        batch_op.drop_column("initiative_id")

    # 6. Tool naming: the initiative toggle column + stored permission keys.
    op.alter_column(
        "initiatives", "calendar_events_enabled", new_column_name="calendars_enabled"
    )
    _swap_permission_key_check(_OLD_PERMISSION_KEYS + _NEW_PERMISSION_KEYS)
    _rewrite_permission_keys(_PERMISSION_KEY_RENAMES)
    _swap_permission_key_check(_NEW_PERMISSION_KEYS)
    _swap_recent_check(_NEW_RECENT_TYPES)

    # 8. Re-assert the registry-rendered RLS: policies for the new tables and
    #    the re-anchored event tables (dropped in step 5) — the same idempotent
    #    DDL provisioning re-runs.
    for statement in rls_statements:
        op.execute(statement)


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)
    op.execute(_recent_views_trigger_fn(_OLD_ENTITY_TABLES))


def _apply_downgrade() -> None:
    _swap_recent_check(_OLD_RECENT_TYPES)
    _swap_permission_key_check(_OLD_PERMISSION_KEYS + _NEW_PERMISSION_KEYS)
    _rewrite_permission_keys([(new, old) for old, new in _PERMISSION_KEY_RENAMES])
    _swap_permission_key_check(_OLD_PERMISSION_KEYS)
    op.alter_column(
        "initiatives", "calendars_enabled", new_column_name="calendar_events_enabled"
    )

    op.add_column(
        "calendar_events", sa.Column("initiative_id", sa.Integer(), nullable=True)
    )
    with _without_force_rls(_FORCE_RLS_DML_TABLES):
        op.execute(
            """
            UPDATE calendar_events
            SET initiative_id = c.initiative_id
            FROM calendars c
            WHERE c.id = calendar_events.calendar_id
            """
        )
        op.execute("DELETE FROM recent_views WHERE entity_type = 'calendar'")
        op.execute("DELETE FROM resource_grants WHERE resource_type = 'calendar'")
        # Best-effort per-event sharing: creator owner + all-members read (the
        # original per-event grant detail was consumed by the upgrade).
        op.execute(
            """
            INSERT INTO resource_grants (
                guild_id, initiative_id, resource_type, resource_id,
                user_id, role_id, level, created_at, all_initiative_members
            )
            SELECT ce.guild_id, ce.initiative_id, 'calendar_event', ce.id,
                   ce.created_by_id, NULL, 'owner', now(), false
            FROM calendar_events ce
            """
        )
        op.execute(
            """
            INSERT INTO resource_grants (
                guild_id, initiative_id, resource_type, resource_id,
                user_id, role_id, level, created_at, all_initiative_members
            )
            SELECT ce.guild_id, ce.initiative_id, 'calendar_event', ce.id,
                   NULL, NULL, 'read', now(), true
            FROM calendar_events ce
            """
        )

    # The current policies read calendar_id (and join calendars, blocking its
    # DROP TABLE below) and must go first. recent_views' policy resolves a
    # recent's initiative through the recentable entity tables — calendars
    # among them — so it blocks the table drop too.
    _drop_initiative_member_policies(_EVENT_POLICY_TABLES + ("recent_views",))
    op.alter_column("calendar_events", "initiative_id", nullable=False)
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendar_events_initiative_id"),
            ["initiative_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("calendar_events_initiative_id_fkey"),
            "initiatives",
            ["initiative_id"],
            ["id"],
        )
        batch_op.drop_index(batch_op.f("ix_calendar_events_calendar_id"))
        batch_op.drop_constraint(
            batch_op.f("calendar_events_calendar_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("calendar_id")

    with op.batch_alter_table("calendar_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendar_tags_tag_id"))
    op.drop_table("calendar_tags")
    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendars_name"))
        batch_op.drop_index(batch_op.f("ix_calendars_initiative_id"))
        batch_op.drop_index(batch_op.f("ix_calendars_guild_id"))
    op.drop_table("calendars")
