"""add galleries tool

A collection of pictures: one ``galleries`` table per guild schema, its tag
junction, the ``gallery_images`` it holds (with their own tags and their
version history), the comment parent that lets a gallery carry a thread, and
the initiative master switch.

Three CHECK constraints carry a vocabulary that just grew, and each is
rewritten rather than extended because Postgres has no "add a value" for one:
the comment single-parent rule, the initiative permission keys, and the
recent-view entity types. Their values are written out literally here rather
than derived from the enums — a migration records what was true at this
revision, and a later enum change must be a later migration.

``public.fn_recent_views_set_guild_id`` gains a ``gallery`` arm for the same
reason: it is a plpgsql CASE that RAISES when nothing matches, so a recentable
type with no arm makes every view of it fail. The function lives in ``public``
and is shared by every guild schema, so it is replaced once.

Every role that predates this revision is also backfilled with the two new
permission rows, at the values a role created today would get — the built-in
``project_manager`` on, every other role at the documented default (off) —
through ``_ROLE_PERMISSION_DEFAULTS`` and the statement in ``backfill_sql``,
copied from 20260907_0233 rather than imported so this revision keeps saying
what it did.

RLS policies, table grants and the ``created_by`` trigger are NOT written
here: provisioning renders those from the live ``guild_template`` and the
registries, and the boot backfill re-applies them to every guild whose stamp
this revision made stale.

Revision ID: 20260909_0248
Revises: 20260909_0247
Create Date: 2026-09-09
"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260909_0248"
down_revision = "20260909_0247"
branch_labels = None
depends_on = None


# Every comment parent after this revision — the task plus one column per tool.
_PARENTS_AFTER = (
    "task_id",
    "document_id",
    "project_id",
    "queue_id",
    "counter_group_id",
    "calendar_id",
    "dashboard_id",
    "post_id",
    "gallery_id",
)
_PARENTS_BEFORE = _PARENTS_AFTER[:-1]

_PERMISSION_KEYS_AFTER = (
    "calendars_enabled",
    "counter_groups_enabled",
    "create_calendars",
    "create_counter_groups",
    "create_dashboards",
    "create_documents",
    "create_galleries",
    "create_posts",
    "create_projects",
    "create_queues",
    "dashboards_enabled",
    "documents_enabled",
    "galleries_enabled",
    "posts_enabled",
    "projects_enabled",
    "queues_enabled",
)
_PERMISSION_KEYS_BEFORE = tuple(
    key
    for key in _PERMISSION_KEYS_AFTER
    if key not in ("create_galleries", "galleries_enabled")
)

#: (entity_type, table) for every recentable tool, in the order the function
#: has always listed them. The CHECK vocabulary below is the same set, sorted.
_RECENT_TABLES_AFTER = (
    ("project", "projects"),
    ("document", "documents"),
    ("queue", "queues"),
    ("counter_group", "counter_groups"),
    ("calendar", "calendars"),
    ("dashboard", "dashboards"),
    ("post", "posts"),
    ("gallery", "galleries"),
)
_RECENT_TABLES_BEFORE = _RECENT_TABLES_AFTER[:-1]

_RECENT_TYPES_AFTER = tuple(sorted(etype for etype, _ in _RECENT_TABLES_AFTER))
_RECENT_TYPES_BEFORE = tuple(t for t in _RECENT_TYPES_AFTER if t != "gallery")

_ROLE_TABLE = "initiative_role_permissions"

# Permission key → the value a role created at this revision stores. Mirrors
# ``DEFAULT_PERMISSION_VALUES`` as it stood here — every key, not only the two
# this revision adds, so a role missing any of them is made whole by one pass:
# viewing a core (always-on) tool is on, viewing an opt-in tool is off,
# creating anything is off.
_ROLE_PERMISSION_DEFAULTS: dict[str, bool] = {
    "projects_enabled": True,
    "documents_enabled": True,
    "queues_enabled": False,
    "counter_groups_enabled": False,
    "calendars_enabled": False,
    "dashboards_enabled": False,
    "posts_enabled": False,
    "galleries_enabled": False,
    "create_projects": False,
    "create_documents": False,
    "create_queues": False,
    "create_counter_groups": False,
    "create_calendars": False,
    "create_dashboards": False,
    "create_posts": False,
    "create_galleries": False,
}


def backfill_sql(defaults: dict[str, bool]) -> str:
    """The INSERT this revision runs, unqualified so it applies in whichever
    guild schema the search_path names. A function rather than a literal so
    the statement can be exercised against a real schema from a test."""
    values = ", ".join(
        f"('{key}', {'true' if enabled else 'false'})"
        for key, enabled in sorted(defaults.items())
    )
    return f"""
        INSERT INTO {_ROLE_TABLE} (initiative_role_id, permission_key, enabled)
        SELECT r.id,
               k.permission_key,
               CASE
                   WHEN r.is_builtin AND r.name = 'project_manager' THEN true
                   ELSE k.enabled
               END
        FROM initiative_roles AS r
        CROSS JOIN (VALUES {values}) AS k(permission_key, enabled)
        ON CONFLICT (initiative_role_id, permission_key) DO NOTHING
    """


def _backfill_role_permissions() -> None:
    # The table already exists, so it needs migration-time write access for
    # this insert; it is restored immediately afterwards either way.
    op.execute(f"ALTER TABLE {_ROLE_TABLE} NO FORCE ROW LEVEL SECURITY")
    try:
        op.execute(backfill_sql(_ROLE_PERMISSION_DEFAULTS))
    finally:
        op.execute(f"ALTER TABLE {_ROLE_TABLE} FORCE ROW LEVEL SECURITY")


#: Asks the next boot to rebuild this guild's search triggers and re-sweep its
#: entries through the registry — which is how the new tables start being
#: indexed.
_CLEAR_SEARCH_GENERATION = "COMMENT ON TABLE search_entries IS NULL"


def _quoted(values) -> str:
    return ", ".join(f"'{value}'" for value in values)


def _single_parent_check(columns) -> str:
    return f"num_nonnulls({', '.join(columns)}) = 1"


def _swap_comment_parent_check(columns) -> None:
    op.execute(
        "ALTER TABLE comments DROP CONSTRAINT IF EXISTS ck_comments_single_parent"
    )
    op.create_check_constraint(
        "ck_comments_single_parent", "comments", _single_parent_check(columns)
    )


def _swap_permission_key_check(keys) -> None:
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "DROP CONSTRAINT IF EXISTS ck_initiative_role_permissions_permission_key"
    )
    op.execute(
        "ALTER TABLE initiative_role_permissions "
        "ADD CONSTRAINT ck_initiative_role_permissions_permission_key "
        f"CHECK (permission_key::text = ANY (ARRAY[{_quoted(keys)}]::text[]))"
    )


def _recent_views_trigger_fn(entity_tables) -> str:
    """``public.fn_recent_views_set_guild_id`` with one CASE arm per recentable
    entity type — the trigger denormalizes ``guild_id`` from the entity's own
    table, and a type with no arm makes every INSERT for it fail."""
    arms = "\n".join(
        f"""                    WHEN '{etype}' THEN
                        SELECT guild_id INTO NEW.guild_id FROM {table}
                        WHERE id = NEW.entity_id;"""
        for etype, table in entity_tables
    )
    return f"""
        CREATE OR REPLACE FUNCTION public.fn_recent_views_set_guild_id() RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.guild_id IS NULL OR (TG_OP = 'UPDATE' AND (
                OLD.entity_type IS DISTINCT FROM NEW.entity_type
                OR OLD.entity_id IS DISTINCT FROM NEW.entity_id
            )) THEN
                CASE NEW.entity_type
{arms}
                    ELSE
                        RAISE EXCEPTION
                            'fn_recent_views_set_guild_id has no arm for entity_type %',
                            NEW.entity_type;
                END CASE;
            END IF;
            RETURN NEW;
        END;
        $$
    """


def _swap_recent_check(types) -> None:
    op.execute(
        "ALTER TABLE recent_views DROP CONSTRAINT IF EXISTS ck_recent_views_entity_type"
    )
    op.execute(
        "ALTER TABLE recent_views ADD CONSTRAINT ck_recent_views_entity_type "
        f"CHECK (entity_type = ANY (ARRAY[{_quoted(types)}]))"
    )


def upgrade() -> None:
    # Shared by every guild schema, so it is rewritten once.
    op.execute(_recent_views_trigger_fn(_RECENT_TABLES_AFTER))
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    op.create_table(
        "galleries",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "comments_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("initiative_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        # The FK to gallery_images is added below, once that table exists.
        sa.Column("cover_image_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.id"]),
        sa.ForeignKeyConstraint(
            ["initiative_id"], ["initiatives.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("galleries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_galleries_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_galleries_initiative_id"), ["initiative_id"], unique=False
        )

    op.create_table(
        "gallery_tags",
        sa.Column("gallery_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gallery_id"], ["galleries.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.PrimaryKeyConstraint("gallery_id", "tag_id"),
    )
    with op.batch_alter_table("gallery_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gallery_tags_tag_id"), ["tag_id"], unique=False
        )

    op.create_table(
        "gallery_images",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("gallery_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("file_url", sa.String(length=512), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column("file_content_type", sa.String(length=128), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.id"]),
        sa.ForeignKeyConstraint(["gallery_id"], ["galleries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("gallery_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gallery_images_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gallery_images_gallery_id"), ["gallery_id"], unique=False
        )
        # The list is always ordered by upload time, and the timeline groups
        # by it.
        batch_op.create_index(
            batch_op.f("ix_gallery_images_created_at"), ["created_at"], unique=False
        )

    # A gallery's chosen cover — one of its own pictures, so the FK points back
    # at the table that points at galleries. SET NULL: removing the picture
    # leaves the gallery with no cover, not no gallery.
    op.create_foreign_key(
        "galleries_cover_image_id_fkey",
        "galleries",
        "gallery_images",
        ["cover_image_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "gallery_image_tags",
        sa.Column("gallery_image_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gallery_image_id"], ["gallery_images.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.PrimaryKeyConstraint("gallery_image_id", "tag_id"),
    )
    with op.batch_alter_table("gallery_image_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gallery_image_tags_tag_id"), ["tag_id"], unique=False
        )

    op.create_table(
        "gallery_image_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gallery_image_id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(length=512), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column("file_content_type", sa.String(length=128), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.id"]),
        sa.ForeignKeyConstraint(
            ["gallery_image_id"], ["gallery_images.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gallery_image_id", "version_number", name="uq_giv_image_version"
        ),
    )
    with op.batch_alter_table("gallery_image_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gallery_image_versions_gallery_image_id"),
            ["gallery_image_id"],
            unique=False,
        )

    # The comment parent. Its FK cascades so deleting a gallery takes its
    # thread with it, matching every other tool parent.
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gallery_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "comments_gallery_id_fkey",
        "comments",
        "galleries",
        ["gallery_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_comments_gallery_id", "comments", ["gallery_id"])
    _swap_comment_parent_check(_PARENTS_AFTER)

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "galleries_enabled",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )

    _swap_permission_key_check(_PERMISSION_KEYS_AFTER)
    _backfill_role_permissions()
    _swap_recent_check(_RECENT_TYPES_AFTER)
    op.execute(_CLEAR_SEARCH_GENERATION)


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)
    op.execute(_recent_views_trigger_fn(_RECENT_TABLES_BEFORE))


#: Tables the downgrade clears gallery rows out of. Row-level security is
#: lifted for the length of those deletes and restored immediately after.
_CLEANUP_TABLES = (
    "comments",
    "recent_views",
    "search_entries",
    "initiative_role_permissions",
)


#: Drops every rendered policy that mentions a gallery, wherever it lives.
#: Read out of the catalog rather than listed here, so a policy this revision
#: did not name is still removed. The next boot re-renders them from the
#: registry.
_DROP_GALLERY_POLICIES = """
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT c.relname, p.polname
        FROM pg_policy p
        JOIN pg_class c ON c.oid = p.polrelid
        WHERE c.relnamespace = current_schema()::regnamespace
          AND (coalesce(pg_get_expr(p.polqual, p.polrelid), '') LIKE '%galler%'
               OR coalesce(pg_get_expr(p.polwithcheck, p.polrelid), '') LIKE '%galler%')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', r.polname, r.relname);
    END LOOP;
END $$;
"""


def _apply_downgrade() -> None:
    op.execute(_DROP_GALLERY_POLICIES)

    for table in _CLEANUP_TABLES:
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
    try:
        op.execute("DELETE FROM comments WHERE gallery_id IS NOT NULL")
        op.execute("DELETE FROM recent_views WHERE entity_type = 'gallery'")
        op.execute(
            "DELETE FROM search_entries WHERE entity_type IN ('gallery', 'gallery_image')"
        )
        op.execute(
            "DELETE FROM initiative_role_permissions WHERE permission_key IN "
            "('create_galleries', 'galleries_enabled')"
        )
    finally:
        for table in _CLEANUP_TABLES:
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

    _swap_recent_check(_RECENT_TYPES_BEFORE)
    _swap_permission_key_check(_PERMISSION_KEYS_BEFORE)

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.drop_column("galleries_enabled")

    _swap_comment_parent_check(_PARENTS_BEFORE)
    op.drop_index("ix_comments_gallery_id", table_name="comments")
    op.drop_constraint("comments_gallery_id_fkey", "comments", type_="foreignkey")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_column("gallery_id")

    op.drop_constraint("galleries_cover_image_id_fkey", "galleries", type_="foreignkey")

    with op.batch_alter_table("gallery_image_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gallery_image_versions_gallery_image_id"))
    op.drop_table("gallery_image_versions")

    with op.batch_alter_table("gallery_image_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gallery_image_tags_tag_id"))
    op.drop_table("gallery_image_tags")

    with op.batch_alter_table("gallery_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gallery_images_created_at"))
        batch_op.drop_index(batch_op.f("ix_gallery_images_gallery_id"))
        batch_op.drop_index(batch_op.f("ix_gallery_images_guild_id"))
    op.drop_table("gallery_images")

    with op.batch_alter_table("gallery_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gallery_tags_tag_id"))
    op.drop_table("gallery_tags")

    with op.batch_alter_table("galleries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_galleries_initiative_id"))
        batch_op.drop_index(batch_op.f("ix_galleries_guild_id"))
    op.drop_table("galleries")

    op.execute(_CLEAR_SEARCH_GENERATION)
