"""wiki settings

What a wiki is *for* differs more than what it is. A club handbook is read
front to back and ordered by hand; a world bible has two hundred entries
nobody orders by hand and lives on "what links here"; a runbook is full of
screenshots and wants the whole screen. These are the settings that let one
tool be all three.

Revision ID: 20260918_0306
Revises: 20260917_0305
Create Date: 2026-09-18
"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260918_0306"
down_revision = "20260917_0305"
branch_labels = None
depends_on = None

#: The columns this revision adds, and the order they are dropped in. Built by
#: a factory rather than held as objects: a Column belongs to one table, and
#: this runs once per guild schema.
_COLUMN_NAMES: tuple[str, ...] = (
    "page_order",
    "accent_color",
    "template_page_id",
    "contents_depth",
    "show_updated_at",
    "show_connections",
    "reading_width",
)


def _columns() -> list[sa.Column]:
    """A fresh set of columns. The defaults are what the tool did before it
    could be asked: the hand-built order, the whole screen, connections shown."""
    return [
        sa.Column(
            "page_order", sa.String(length=16), server_default="manual", nullable=False
        ),
        sa.Column("accent_color", sa.String(length=32), nullable=True),
        sa.Column("template_page_id", sa.Integer(), nullable=True),
        sa.Column(
            "contents_depth", sa.Integer(), server_default=sa.text("3"), nullable=False
        ),
        sa.Column(
            "show_updated_at",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "show_connections",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "reading_width", sa.String(length=16), server_default="wide", nullable=False
        ),
    ]


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    with op.batch_alter_table("wikis", schema=None) as batch_op:
        for column in _columns():
            batch_op.add_column(column)

    # The template is one of the wiki's own pages, so the two tables point at
    # each other — added after both exist, as the home page's key is.
    op.create_foreign_key(
        "wikis_template_page_id_fkey",
        "wikis",
        "wiki_pages",
        ["template_page_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # These settings change what a page's body is indexed as read through, not
    # what is indexed, so the search stamp stands.


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    op.drop_constraint("wikis_template_page_id_fkey", "wikis", type_="foreignkey")
    with op.batch_alter_table("wikis", schema=None) as batch_op:
        for name in reversed(_COLUMN_NAMES):
            batch_op.drop_column(name)
