"""drop calendar event color

Color lives on the calendar, not the event: an event renders in its
calendar's color. The per-event override column goes away (existing
values are dropped; the downgrade restores an empty column).
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260806_0158"
down_revision = "20260804_0157"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_column("color")

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "color", sa.VARCHAR(length=32), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
