"""app pairwise subjects

What one installed app calls one member. Own-row like the other member-owned
guild tables — the owner, or a guild admin routed into the guild — because the
link between subject and member is the whole value: a row readable by anyone in
the guild would undo the unlinkability it exists to provide, and a writable one
would point an app's delegated calls at a different person.

The policies are written here as well as rendered at provisioning time, so a
guild that does not re-provision before its next request still has them.
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260814_0180"
down_revision = "20260814_0179"
branch_labels = None
depends_on = None

_TABLE = "guild_app_subjects"

#: Owner-or-guild-admin, matching the rendered own-row predicate exactly (see
#: ``app.db.guild_ddl._OWN_ROW_PREDICATE``). The cast is NULLIF-guarded because
#: an unset context leaves the setting empty and a bare ``''::int`` would raise
#: for every row the policy is evaluated against.
_OWN_ROW_PREDICATE = (
    "(user_id = NULLIF(current_setting('app.current_user_id'::text, true), '')::int"
    " OR current_setting('app.current_guild_role'::text, true) = 'admin'::text)"
)

_OWN_ROW_POLICIES = (
    ("own_row_select", "SELECT", "USING"),
    ("own_row_insert", "INSERT", "WITH CHECK"),
    ("own_row_update", "UPDATE", "USING-CHECK"),
    ("own_row_delete", "DELETE", "USING"),
)


def _own_row_rls_statements() -> list[str]:
    statements = [
        f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY",
        f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY",
    ]
    for name, command, clause in _OWN_ROW_POLICIES:
        statements.append(f"DROP POLICY IF EXISTS {name} ON {_TABLE}")
        head = f"CREATE POLICY {name} ON {_TABLE} AS PERMISSIVE FOR {command}"
        if clause == "USING-CHECK":
            statements.append(
                f"{head} USING ({_OWN_ROW_PREDICATE}) WITH CHECK ({_OWN_ROW_PREDICATE})"
            )
        elif clause == "WITH CHECK":
            statements.append(f"{head} WITH CHECK ({_OWN_ROW_PREDICATE})")
        else:
            statements.append(f"{head} USING ({_OWN_ROW_PREDICATE})")
    return statements


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_app_subjects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["guild_apps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "app_id", "user_id", name="guild_app_subjects_unique_member"
        ),
        sa.UniqueConstraint("subject", name="guild_app_subjects_unique_subject"),
    )
    with op.batch_alter_table("guild_app_subjects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guild_app_subjects_app_id"), ["app_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_guild_app_subjects_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_guild_app_subjects_user_id"), ["user_id"], unique=False
        )

    for statement in _own_row_rls_statements():
        op.execute(sa.text(statement))


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    for name, _command, _clause in _OWN_ROW_POLICIES:
        op.execute(sa.text(f"DROP POLICY IF EXISTS {name} ON {_TABLE}"))
    op.execute(sa.text(f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY"))

    with op.batch_alter_table("guild_app_subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guild_app_subjects_user_id"))
        batch_op.drop_index(batch_op.f("ix_guild_app_subjects_guild_id"))
        batch_op.drop_index(batch_op.f("ix_guild_app_subjects_app_id"))

    op.drop_table("guild_app_subjects")
    # ### end Alembic commands ###
