"""app pairwise subjects"""

revision = '20260814_0180'
down_revision = '20260814_0179'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from app.db.guild_migrations import run_for_each_guild_schema



def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_app_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['guild_apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'user_id', name='guild_app_subjects_unique_member'),
    sa.UniqueConstraint('subject', name='guild_app_subjects_unique_subject')
    )
    with op.batch_alter_table('guild_app_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_app_subjects_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_app_subjects_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_app_subjects_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_app_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_app_subjects_user_id'))
        batch_op.drop_index(batch_op.f('ix_guild_app_subjects_guild_id'))
        batch_op.drop_index(batch_op.f('ix_guild_app_subjects_app_id'))

    op.drop_table('guild_app_subjects')
    # ### end Alembic commands ###
