"""add tasks.completed_at

A task is complete exactly when its status sits in the ``done`` category;
``completed_at`` records when it got there, so consumers stop proxying
completion with ``updated_at``.

Existing done tasks are backfilled from ``updated_at`` — the same proxy the
stats service already used for completion time, so no reader gets a worse
answer than it had, and the "done implies a completion timestamp" invariant
holds from the first boot after the upgrade.

The backfill runs as the table owner with FORCE RLS toggled off around it
(FORCE would leave the owner policy-bound and silently skip every row, since a
migration carries no request context) and asserts no done task is left without
a timestamp per schema.
"""

import sqlalchemy as sa
from alembic import op
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260810_0160"
down_revision = "20260806_0159"
branch_labels = None
depends_on = None

_BACKFILL = """
UPDATE tasks
   SET completed_at = tasks.updated_at
  FROM task_statuses
 WHERE tasks.task_status_id = task_statuses.id
   AND task_statuses.category = 'done'
   AND tasks.completed_at IS NULL
"""

_REMAINING = """
SELECT count(*)
  FROM tasks
  JOIN task_statuses ON task_statuses.id = tasks.task_status_id
 WHERE task_statuses.category = 'done'
   AND tasks.completed_at IS NULL
"""


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
        )

    op.execute("ALTER TABLE tasks NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE task_statuses NO FORCE ROW LEVEL SECURITY")
    try:
        op.execute(sa.text(_BACKFILL))
        remaining = op.get_bind().execute(sa.text(_REMAINING)).scalar()
        if remaining:
            raise RuntimeError(
                f"{remaining} done tasks still have no completed_at after backfill"
            )
    finally:
        op.execute("ALTER TABLE task_statuses FORCE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE tasks FORCE ROW LEVEL SECURITY")


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("completed_at")
