"""app install auto update

Whether an install tracks its listing's published versions. The default is
``true``, and the backfill it implies is the intended one: an install made
before this column existed starts tracking, because tracking is what an install
does unless its guild says otherwise.
"""

import sqlalchemy as sa
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260825_0194"
down_revision = "20260822_0193"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_apps", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_update", sa.Boolean(), server_default="true", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_apps", schema=None) as batch_op:
        batch_op.drop_column("auto_update")

    # ### end Alembic commands ###
