"""A comment can name who said it elsewhere.

An import matches a comment's author to an account where it can, one row at a
time, in the wizard's people step. Where it cannot, the name still travelled
and has nowhere to go: ``created_by`` names the import that wrote the row, and
crediting that account with somebody else's words would be wrong.

``imported_author_name`` is where the source's own answer goes. Display text,
nullable, and null on every comment written in this app.

Revision ID: 20260920_0323
Revises: 20260919_0322
Create Date: 2026-09-20
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260920_0323"
down_revision = "20260919_0322"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("imported_author_name", sa.String(length=200), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_column("imported_author_name")

    # ### end Alembic commands ###
