"""initiative discovery

Per-initiative join policy plus the table backing the request flow.

``join_policy`` defaults to ``private`` — today's behaviour — so every existing
initiative, the ``is_default`` one included, migrates closed and opening one is
an explicit action after upgrade. ``auto_join`` is false for the same reason,
and its CHECK ties it to ``open``: an initiative people are enrolled in
automatically has to be one they could also find and rejoin.

``initiative_join_requests`` ships whole here even though only the policy,
directory, and self-join paths are wired up — one table migration rather than
two. The partial unique index is what keeps a user from stacking requests while
leaving resolved rows behind as history.
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260828_0199"
down_revision = "20260828_0198"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initiative_join_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("initiative_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'denied')",
            name="ck_initiative_join_requests_status",
        ),
        sa.ForeignKeyConstraint(
            ["initiative_id"], ["initiatives.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("initiative_join_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_initiative_join_requests_initiative_id"),
            ["initiative_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_initiative_join_requests_user_id"),
            ["user_id"],
            unique=False,
        )
        batch_op.create_index(
            "uq_initiative_join_requests_pending",
            ["initiative_id", "user_id"],
            unique=True,
            postgresql_where=sa.text("status = 'pending'"),
        )

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "join_policy",
                sa.String(length=20),
                server_default="private",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("auto_join", sa.Boolean(), server_default="false", nullable=False)
        )

    # ### end Alembic commands ###

    # Hand-added: alembic's autogenerate does not diff CHECK constraints, so the
    # two guarding the columns above are declared here (they are on the model in
    # `Initiative.__table_args__`).
    op.create_check_constraint(
        "ck_initiatives_join_policy",
        "initiatives",
        "join_policy IN ('private', 'request', 'open')",
    )
    op.create_check_constraint(
        "ck_initiatives_auto_join_open",
        "initiatives",
        "(NOT auto_join) OR join_policy = 'open'",
    )


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    op.drop_constraint("ck_initiatives_auto_join_open", "initiatives", type_="check")
    op.drop_constraint("ck_initiatives_join_policy", "initiatives", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.drop_column("auto_join")
        batch_op.drop_column("join_policy")

    with op.batch_alter_table("initiative_join_requests", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_initiative_join_requests_pending",
            postgresql_where=sa.text("status = 'pending'"),
        )
        batch_op.drop_index(batch_op.f("ix_initiative_join_requests_user_id"))
        batch_op.drop_index(batch_op.f("ix_initiative_join_requests_initiative_id"))

    op.drop_table("initiative_join_requests")
    # ### end Alembic commands ###
