"""add guild AI connection and member key tables"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260803_0154"
down_revision = "20260720_0153"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_ai_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("base_url", sa.String(length=1000), nullable=True),
        sa.Column("model", sa.String(length=500), nullable=True),
        sa.Column("api_key_encrypted", sa.String(length=2000), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "allow_member_keys",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guild_ai_connections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guild_ai_connections_guild_id"), ["guild_id"], unique=False
        )

    op.create_table(
        "guild_ai_member_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("connection_scope", sa.String(length=20), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("api_key_encrypted", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "connection_scope",
            "connection_id",
            name="uq_ai_member_key_user_connection",
        ),
    )
    with op.batch_alter_table("guild_ai_member_keys", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guild_ai_member_keys_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_guild_ai_member_keys_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "guild_ai_member_prefs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("connection_scope", sa.String(length=20), nullable=True),
        sa.Column("connection_id", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guild_ai_member_prefs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guild_ai_member_prefs_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_guild_ai_member_prefs_user_id"), ["user_id"], unique=True
        )

    # Preserve a guild that had configured a provider on guild_settings: copy it
    # into a guild_ai_connections row (keeping the encrypted key) before the old
    # columns are dropped. Runs per guild schema (search_path is guild_<id>);
    # guild_template has no rows so it copies nothing. The provider column is the
    # discriminator — a guild with no provider set had no usable config.
    op.execute(
        sa.text(
            """
            INSERT INTO guild_ai_connections
                (guild_id, label, provider, base_url, model,
                 api_key_encrypted, enabled, is_default, created_at, updated_at)
            SELECT guild_id, 'Imported connection', ai_provider, ai_base_url,
                   ai_model, ai_api_key_encrypted, COALESCE(ai_enabled, true),
                   true, now(), now()
            FROM guild_settings
            WHERE ai_provider IS NOT NULL
            """
        )
    )

    with op.batch_alter_table("guild_settings", schema=None) as batch_op:
        batch_op.drop_column("ai_base_url")
        batch_op.drop_column("ai_enabled")
        batch_op.drop_column("ai_model")
        batch_op.drop_column("ai_provider")
        batch_op.drop_column("ai_allow_user_override")
        batch_op.drop_column("ai_api_key_encrypted")

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ai_api_key_encrypted",
                sa.VARCHAR(length=2000),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "ai_allow_user_override",
                sa.BOOLEAN(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "ai_provider", sa.VARCHAR(length=50), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "ai_model", sa.VARCHAR(length=500), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("ai_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "ai_base_url",
                sa.VARCHAR(length=1000),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("guild_ai_member_prefs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guild_ai_member_prefs_user_id"))
        batch_op.drop_index(batch_op.f("ix_guild_ai_member_prefs_guild_id"))

    op.drop_table("guild_ai_member_prefs")
    with op.batch_alter_table("guild_ai_member_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guild_ai_member_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_guild_ai_member_keys_guild_id"))

    op.drop_table("guild_ai_member_keys")
    with op.batch_alter_table("guild_ai_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guild_ai_connections_guild_id"))

    op.drop_table("guild_ai_connections")
    # ### end Alembic commands ###
