"""guild apps table

Installation state for apps mounted at guild scope: which listing, at which
version, and whatever the app needs to find the content it created. The content
itself lives in the ordinary tables (a guild-level ``calendars`` row, say) and is
governed by its own grants — this table records only that the app is installed.

Guild-level, so it carries no initiative RLS: the schema boundary confines it to
its guild, every member may read it (the sidebar has to know an app is there),
and installing or removing one is gated at the endpoint.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260812_0167"
down_revision = "20260812_0166"
branch_labels = None
depends_on = None


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_apps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("listing_uid", sa.String(length=14), nullable=False),
        sa.Column("listing_version", sa.String(length=32), nullable=False),
        sa.Column("app_kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "definition",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("installed_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["installed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id", "listing_uid", name="guild_apps_unique_listing"
        ),
    )
    with op.batch_alter_table("guild_apps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guild_apps_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_guild_apps_listing_uid"), ["listing_uid"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_apps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guild_apps_listing_uid"))
        batch_op.drop_index(batch_op.f("ix_guild_apps_guild_id"))

    op.drop_table("guild_apps")
    # ### end Alembic commands ###
