"""app user delegations

Each member's own answer to whether an installed app may act as them, and how
deeply. Guild-level rather than initiative-scoped — an app is guild-wide and the
row has no initiative to resolve — with the same ``own_row_*`` policies the
other member-owned guild tables carry: the owner, or a guild admin routed into
the guild.

The policies are written here as well as rendered at provisioning time, so a
guild that does not re-provision before its next request still has them.
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — autogenerated types (AutoString) reference it
from alembic import op

from app.db.guild_migrations import run_for_each_guild_schema

revision = "20260814_0178"
down_revision = "20260814_0177"
branch_labels = None
depends_on = None

_TABLE = "guild_app_user_delegations"

#: Owner-or-guild-admin, matching the rendered own-row predicate exactly (see
#: ``app.db.guild_ddl._OWN_ROW_PREDICATE``). The cast is NULLIF-guarded because
#: an unset context leaves the setting empty and a bare ``''::int`` would raise
#: for every row the policy is evaluated against.
_OWN_ROW_PREDICATE = (
    "(user_id = NULLIF(current_setting('app.current_user_id'::text, true), '')::int"
    " OR current_setting('app.current_guild_role'::text, true) = 'admin'::text)"
)

_OWN_ROW_POLICIES = (
    ("own_row_select", "SELECT", "USING"),
    ("own_row_insert", "INSERT", "WITH CHECK"),
    ("own_row_update", "UPDATE", "USING-CHECK"),
    ("own_row_delete", "DELETE", "USING"),
)


def _own_row_rls_statements() -> list[str]:
    statements = [
        f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY",
        f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY",
    ]
    for name, command, clause in _OWN_ROW_POLICIES:
        statements.append(f"DROP POLICY IF EXISTS {name} ON {_TABLE}")
        head = f"CREATE POLICY {name} ON {_TABLE} AS PERMISSIVE FOR {command}"
        if clause == "USING-CHECK":
            statements.append(
                f"{head} USING ({_OWN_ROW_PREDICATE}) WITH CHECK ({_OWN_ROW_PREDICATE})"
            )
        elif clause == "WITH CHECK":
            statements.append(f"{head} WITH CHECK ({_OWN_ROW_PREDICATE})")
        else:
            statements.append(f"{head} USING ({_OWN_ROW_PREDICATE})")
    return statements


def upgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_upgrade)


def _apply_upgrade() -> None:
    op.create_table(
        _TABLE,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("can_read", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_write", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_id", sa.Integer(), nullable=True),
        sa.Column("confirmed_factor", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["guild_apps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.id"]),
        sa.ForeignKeyConstraint(["revoked_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "app_id", "user_id", name="guild_app_user_delegations_unique_member"
        ),
    )
    with op.batch_alter_table(_TABLE, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guild_app_user_delegations_app_id"),
            ["app_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_guild_app_user_delegations_guild_id"),
            ["guild_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_guild_app_user_delegations_user_id"),
            ["user_id"],
            unique=False,
        )

    for statement in _own_row_rls_statements():
        op.execute(sa.text(statement))


def downgrade() -> None:
    run_for_each_guild_schema(op.get_bind(), _apply_downgrade)


def _apply_downgrade() -> None:
    for name, _command, _clause in _OWN_ROW_POLICIES:
        op.execute(sa.text(f"DROP POLICY IF EXISTS {name} ON {_TABLE}"))
    op.execute(sa.text(f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY"))

    with op.batch_alter_table(_TABLE, schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guild_app_user_delegations_user_id"))
        batch_op.drop_index(batch_op.f("ix_guild_app_user_delegations_guild_id"))
        batch_op.drop_index(batch_op.f("ix_guild_app_user_delegations_app_id"))

    op.drop_table(_TABLE)
