-- AUTOGENERATED companion to guild_schema.sql: initiative-member-level RLS for the
-- per-guild CONTENT tables. Schema-relative (run with search_path =
-- <guild_schema>, public). Idempotent.
--
-- The access RULE lives in ONE place, public.initiative_access (initiative member
-- OR guild admin OR PAM, read from the request GUCs); each policy below is just the
-- join that resolves a table's initiative id and defers to it.
--
-- SCOPE: only CONTENT tables are here. The STRUCTURAL initiative tables
-- (initiatives, initiative_members, initiative_roles, initiative_role_permissions)
-- are deliberately NOT initiative-member-scoped: they are guild-scoped by the
-- schema boundary (you never query them outside a guild context), the membership
-- table must not be gated by the membership check it backs (that is an infinite
-- recursion), and own-row scoping there would break co-member rosters. The app
-- layer still does any finer filtering (e.g. the initiatives list shows
-- member-only for non-admins).
--
-- To add a new initiative-scoped CONTENT table: copy a block and adjust the
-- initiative-id path. Derived from the legacy public initiative_member_select
-- predicates (the authoritative join paths).


ALTER TABLE calendar_event_attendees ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_event_attendees FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON calendar_event_attendees;
CREATE POLICY initiative_member_select ON calendar_event_attendees AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_attendees.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON calendar_event_attendees;
CREATE POLICY initiative_member_insert ON calendar_event_attendees AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_attendees.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON calendar_event_attendees;
CREATE POLICY initiative_member_update ON calendar_event_attendees AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_attendees.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_attendees.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON calendar_event_attendees;
CREATE POLICY initiative_member_delete ON calendar_event_attendees AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_attendees.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE calendar_event_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_event_documents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON calendar_event_documents;
CREATE POLICY initiative_member_select ON calendar_event_documents AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_documents.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON calendar_event_documents;
CREATE POLICY initiative_member_insert ON calendar_event_documents AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_documents.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON calendar_event_documents;
CREATE POLICY initiative_member_update ON calendar_event_documents AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_documents.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_documents.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON calendar_event_documents;
CREATE POLICY initiative_member_delete ON calendar_event_documents AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_documents.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE calendar_event_property_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_event_property_values FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON calendar_event_property_values;
CREATE POLICY initiative_member_select ON calendar_event_property_values AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM (calendar_events ce JOIN property_definitions pd ON ((pd.id = calendar_event_property_values.property_id))) WHERE ((ce.id = calendar_event_property_values.event_id) AND (ce.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON calendar_event_property_values;
CREATE POLICY initiative_member_insert ON calendar_event_property_values AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM (calendar_events ce JOIN property_definitions pd ON ((pd.id = calendar_event_property_values.property_id))) WHERE ((ce.id = calendar_event_property_values.event_id) AND (ce.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON calendar_event_property_values;
CREATE POLICY initiative_member_update ON calendar_event_property_values AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM (calendar_events ce JOIN property_definitions pd ON ((pd.id = calendar_event_property_values.property_id))) WHERE ((ce.id = calendar_event_property_values.event_id) AND (ce.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (calendar_events ce JOIN property_definitions pd ON ((pd.id = calendar_event_property_values.property_id))) WHERE ((ce.id = calendar_event_property_values.event_id) AND (ce.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON calendar_event_property_values;
CREATE POLICY initiative_member_delete ON calendar_event_property_values AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM (calendar_events ce JOIN property_definitions pd ON ((pd.id = calendar_event_property_values.property_id))) WHERE ((ce.id = calendar_event_property_values.event_id) AND (ce.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE calendar_event_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_event_tags FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON calendar_event_tags;
CREATE POLICY initiative_member_select ON calendar_event_tags AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_tags.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON calendar_event_tags;
CREATE POLICY initiative_member_insert ON calendar_event_tags AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_tags.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON calendar_event_tags;
CREATE POLICY initiative_member_update ON calendar_event_tags AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_tags.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_tags.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON calendar_event_tags;
CREATE POLICY initiative_member_delete ON calendar_event_tags AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM calendar_events WHERE ((calendar_events.id = calendar_event_tags.calendar_event_id) AND public.initiative_access(calendar_events.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON calendar_events;
CREATE POLICY initiative_member_select ON calendar_events AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = calendar_events.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON calendar_events;
CREATE POLICY initiative_member_insert ON calendar_events AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = calendar_events.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON calendar_events;
CREATE POLICY initiative_member_update ON calendar_events AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = calendar_events.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = calendar_events.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON calendar_events;
CREATE POLICY initiative_member_delete ON calendar_events AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = calendar_events.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE counter_group_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE counter_group_permissions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON counter_group_permissions;
CREATE POLICY initiative_member_select ON counter_group_permissions AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON counter_group_permissions;
CREATE POLICY initiative_member_insert ON counter_group_permissions AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON counter_group_permissions;
CREATE POLICY initiative_member_update ON counter_group_permissions AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON counter_group_permissions;
CREATE POLICY initiative_member_delete ON counter_group_permissions AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE counter_group_role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE counter_group_role_permissions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON counter_group_role_permissions;
CREATE POLICY initiative_member_select ON counter_group_role_permissions AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_role_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON counter_group_role_permissions;
CREATE POLICY initiative_member_insert ON counter_group_role_permissions AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_role_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON counter_group_role_permissions;
CREATE POLICY initiative_member_update ON counter_group_role_permissions AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_role_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_role_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON counter_group_role_permissions;
CREATE POLICY initiative_member_delete ON counter_group_role_permissions AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counter_group_role_permissions.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE counter_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE counter_groups FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON counter_groups;
CREATE POLICY initiative_member_select ON counter_groups AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = counter_groups.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON counter_groups;
CREATE POLICY initiative_member_insert ON counter_groups AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = counter_groups.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON counter_groups;
CREATE POLICY initiative_member_update ON counter_groups AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = counter_groups.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = counter_groups.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON counter_groups;
CREATE POLICY initiative_member_delete ON counter_groups AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = counter_groups.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE counters FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON counters;
CREATE POLICY initiative_member_select ON counters AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counters.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON counters;
CREATE POLICY initiative_member_insert ON counters AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counters.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON counters;
CREATE POLICY initiative_member_update ON counters AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counters.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counters.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON counters;
CREATE POLICY initiative_member_delete ON counters AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM counter_groups WHERE ((counter_groups.id = counters.counter_group_id) AND public.initiative_access(counter_groups.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE document_property_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_property_values FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON document_property_values;
CREATE POLICY initiative_member_select ON document_property_values AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM (documents d JOIN property_definitions pd ON ((pd.id = document_property_values.property_id))) WHERE ((d.id = document_property_values.document_id) AND (d.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON document_property_values;
CREATE POLICY initiative_member_insert ON document_property_values AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM (documents d JOIN property_definitions pd ON ((pd.id = document_property_values.property_id))) WHERE ((d.id = document_property_values.document_id) AND (d.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON document_property_values;
CREATE POLICY initiative_member_update ON document_property_values AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM (documents d JOIN property_definitions pd ON ((pd.id = document_property_values.property_id))) WHERE ((d.id = document_property_values.document_id) AND (d.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (documents d JOIN property_definitions pd ON ((pd.id = document_property_values.property_id))) WHERE ((d.id = document_property_values.document_id) AND (d.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON document_property_values;
CREATE POLICY initiative_member_delete ON document_property_values AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM (documents d JOIN property_definitions pd ON ((pd.id = document_property_values.property_id))) WHERE ((d.id = document_property_values.document_id) AND (d.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE document_role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_role_permissions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON document_role_permissions;
CREATE POLICY initiative_member_select ON document_role_permissions AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = document_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON document_role_permissions;
CREATE POLICY initiative_member_insert ON document_role_permissions AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = document_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON document_role_permissions;
CREATE POLICY initiative_member_update ON document_role_permissions AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = document_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = document_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON document_role_permissions;
CREATE POLICY initiative_member_delete ON document_role_permissions AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = document_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON documents;
CREATE POLICY initiative_member_select ON documents AS PERMISSIVE FOR SELECT
  USING (public.initiative_access(documents.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false));
DROP POLICY IF EXISTS initiative_member_insert ON documents;
CREATE POLICY initiative_member_insert ON documents AS PERMISSIVE FOR INSERT
  WITH CHECK (public.initiative_access(documents.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true));
DROP POLICY IF EXISTS initiative_member_update ON documents;
CREATE POLICY initiative_member_update ON documents AS PERMISSIVE FOR UPDATE
  USING (public.initiative_access(documents.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)) WITH CHECK (public.initiative_access(documents.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true));
DROP POLICY IF EXISTS initiative_member_delete ON documents;
CREATE POLICY initiative_member_delete ON documents AS PERMISSIVE FOR DELETE
  USING (public.initiative_access(documents.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true));

ALTER TABLE project_role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_role_permissions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON project_role_permissions;
CREATE POLICY initiative_member_select ON project_role_permissions AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = project_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON project_role_permissions;
CREATE POLICY initiative_member_insert ON project_role_permissions AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = project_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON project_role_permissions;
CREATE POLICY initiative_member_update ON project_role_permissions AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = project_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = project_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON project_role_permissions;
CREATE POLICY initiative_member_delete ON project_role_permissions AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM initiative_roles WHERE ((initiative_roles.id = project_role_permissions.initiative_role_id) AND public.initiative_access(initiative_roles.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON projects;
CREATE POLICY initiative_member_select ON projects AS PERMISSIVE FOR SELECT
  USING (public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false));
DROP POLICY IF EXISTS initiative_member_insert ON projects;
CREATE POLICY initiative_member_insert ON projects AS PERMISSIVE FOR INSERT
  WITH CHECK (public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true));
DROP POLICY IF EXISTS initiative_member_update ON projects;
CREATE POLICY initiative_member_update ON projects AS PERMISSIVE FOR UPDATE
  USING (public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)) WITH CHECK (public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true));
DROP POLICY IF EXISTS initiative_member_delete ON projects;
CREATE POLICY initiative_member_delete ON projects AS PERMISSIVE FOR DELETE
  USING (public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true));

ALTER TABLE property_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_definitions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON property_definitions;
CREATE POLICY initiative_member_select ON property_definitions AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = property_definitions.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON property_definitions;
CREATE POLICY initiative_member_insert ON property_definitions AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = property_definitions.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON property_definitions;
CREATE POLICY initiative_member_update ON property_definitions AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = property_definitions.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = property_definitions.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON property_definitions;
CREATE POLICY initiative_member_delete ON property_definitions AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = property_definitions.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE queue_item_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE queue_item_documents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON queue_item_documents;
CREATE POLICY initiative_member_select ON queue_item_documents AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_documents.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON queue_item_documents;
CREATE POLICY initiative_member_insert ON queue_item_documents AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_documents.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON queue_item_documents;
CREATE POLICY initiative_member_update ON queue_item_documents AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_documents.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_documents.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON queue_item_documents;
CREATE POLICY initiative_member_delete ON queue_item_documents AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_documents.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE queue_item_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE queue_item_tags FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON queue_item_tags;
CREATE POLICY initiative_member_select ON queue_item_tags AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tags.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON queue_item_tags;
CREATE POLICY initiative_member_insert ON queue_item_tags AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tags.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON queue_item_tags;
CREATE POLICY initiative_member_update ON queue_item_tags AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tags.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tags.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON queue_item_tags;
CREATE POLICY initiative_member_delete ON queue_item_tags AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tags.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE queue_item_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE queue_item_tasks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON queue_item_tasks;
CREATE POLICY initiative_member_select ON queue_item_tasks AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tasks.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON queue_item_tasks;
CREATE POLICY initiative_member_insert ON queue_item_tasks AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tasks.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON queue_item_tasks;
CREATE POLICY initiative_member_update ON queue_item_tasks AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tasks.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tasks.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON queue_item_tasks;
CREATE POLICY initiative_member_delete ON queue_item_tasks AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM (queue_items JOIN queues ON ((queues.id = queue_items.queue_id))) WHERE ((queue_items.id = queue_item_tasks.queue_item_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE queue_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE queue_items FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON queue_items;
CREATE POLICY initiative_member_select ON queue_items AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_items.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON queue_items;
CREATE POLICY initiative_member_insert ON queue_items AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_items.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON queue_items;
CREATE POLICY initiative_member_update ON queue_items AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_items.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_items.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON queue_items;
CREATE POLICY initiative_member_delete ON queue_items AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_items.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE queue_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE queue_permissions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON queue_permissions;
CREATE POLICY initiative_member_select ON queue_permissions AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON queue_permissions;
CREATE POLICY initiative_member_insert ON queue_permissions AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON queue_permissions;
CREATE POLICY initiative_member_update ON queue_permissions AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON queue_permissions;
CREATE POLICY initiative_member_delete ON queue_permissions AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE queue_role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE queue_role_permissions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON queue_role_permissions;
CREATE POLICY initiative_member_select ON queue_role_permissions AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_role_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON queue_role_permissions;
CREATE POLICY initiative_member_insert ON queue_role_permissions AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_role_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON queue_role_permissions;
CREATE POLICY initiative_member_update ON queue_role_permissions AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_role_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_role_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON queue_role_permissions;
CREATE POLICY initiative_member_delete ON queue_role_permissions AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM queues WHERE ((queues.id = queue_role_permissions.queue_id) AND public.initiative_access(queues.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE queues ENABLE ROW LEVEL SECURITY;
ALTER TABLE queues FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON queues;
CREATE POLICY initiative_member_select ON queues AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = queues.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON queues;
CREATE POLICY initiative_member_insert ON queues AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = queues.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON queues;
CREATE POLICY initiative_member_update ON queues AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = queues.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = queues.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON queues;
CREATE POLICY initiative_member_delete ON queues AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM initiatives WHERE ((initiatives.id = queues.initiative_id) AND public.initiative_access(initiatives.id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE subtasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE subtasks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON subtasks;
CREATE POLICY initiative_member_select ON subtasks AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = subtasks.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON subtasks;
CREATE POLICY initiative_member_insert ON subtasks AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = subtasks.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON subtasks;
CREATE POLICY initiative_member_update ON subtasks AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = subtasks.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = subtasks.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON subtasks;
CREATE POLICY initiative_member_delete ON subtasks AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = subtasks.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE task_assignees ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_assignees FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON task_assignees;
CREATE POLICY initiative_member_select ON task_assignees AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = task_assignees.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON task_assignees;
CREATE POLICY initiative_member_insert ON task_assignees AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = task_assignees.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON task_assignees;
CREATE POLICY initiative_member_update ON task_assignees AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = task_assignees.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = task_assignees.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON task_assignees;
CREATE POLICY initiative_member_delete ON task_assignees AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM (tasks JOIN projects ON ((projects.id = tasks.project_id))) WHERE ((tasks.id = task_assignees.task_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE task_property_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_property_values FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON task_property_values;
CREATE POLICY initiative_member_select ON task_property_values AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM ((tasks t JOIN projects proj ON ((proj.id = t.project_id))) JOIN property_definitions pd ON ((pd.id = task_property_values.property_id))) WHERE ((t.id = task_property_values.task_id) AND (proj.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON task_property_values;
CREATE POLICY initiative_member_insert ON task_property_values AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM ((tasks t JOIN projects proj ON ((proj.id = t.project_id))) JOIN property_definitions pd ON ((pd.id = task_property_values.property_id))) WHERE ((t.id = task_property_values.task_id) AND (proj.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON task_property_values;
CREATE POLICY initiative_member_update ON task_property_values AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM ((tasks t JOIN projects proj ON ((proj.id = t.project_id))) JOIN property_definitions pd ON ((pd.id = task_property_values.property_id))) WHERE ((t.id = task_property_values.task_id) AND (proj.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM ((tasks t JOIN projects proj ON ((proj.id = t.project_id))) JOIN property_definitions pd ON ((pd.id = task_property_values.property_id))) WHERE ((t.id = task_property_values.task_id) AND (proj.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON task_property_values;
CREATE POLICY initiative_member_delete ON task_property_values AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM ((tasks t JOIN projects proj ON ((proj.id = t.project_id))) JOIN property_definitions pd ON ((pd.id = task_property_values.property_id))) WHERE ((t.id = task_property_values.task_id) AND (proj.initiative_id = pd.initiative_id) AND public.initiative_access(pd.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE task_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_statuses FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON task_statuses;
CREATE POLICY initiative_member_select ON task_statuses AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = task_statuses.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON task_statuses;
CREATE POLICY initiative_member_insert ON task_statuses AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = task_statuses.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON task_statuses;
CREATE POLICY initiative_member_update ON task_statuses AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = task_statuses.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = task_statuses.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON task_statuses;
CREATE POLICY initiative_member_delete ON task_statuses AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = task_statuses.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS initiative_member_select ON tasks;
CREATE POLICY initiative_member_select ON tasks AS PERMISSIVE FOR SELECT
  USING ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = tasks.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, false)))));
DROP POLICY IF EXISTS initiative_member_insert ON tasks;
CREATE POLICY initiative_member_insert ON tasks AS PERMISSIVE FOR INSERT
  WITH CHECK ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = tasks.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_update ON tasks;
CREATE POLICY initiative_member_update ON tasks AS PERMISSIVE FOR UPDATE
  USING ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = tasks.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = tasks.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
DROP POLICY IF EXISTS initiative_member_delete ON tasks;
CREATE POLICY initiative_member_delete ON tasks AS PERMISSIVE FOR DELETE
  USING ((EXISTS ( SELECT 1 FROM projects WHERE ((projects.id = tasks.project_id) AND public.initiative_access(projects.initiative_id, (NULLIF(current_setting('app.current_user_id'::text, true), ''::text))::integer, true)))));
