-- AUTOGENERATED by scripts/gen_guild_schema.py from the public schema Alembic
-- builds. This is THE source for a guild schema's structure. Schema-relative:
-- run with search_path = <guild_schema>, public. Idempotent. Do not hand-edit;
-- regenerate after any guild-scoped schema migration.

CREATE TABLE IF NOT EXISTS calendar_event_attendees (
	calendar_event_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	rsvp_status rsvp_status DEFAULT 'pending'::rsvp_status NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT calendar_event_attendees_pkey PRIMARY KEY (calendar_event_id, user_id)
);
CREATE TABLE IF NOT EXISTS calendar_event_documents (
	calendar_event_id INTEGER NOT NULL, 
	document_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	attached_by_id INTEGER, 
	attached_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT calendar_event_documents_pkey PRIMARY KEY (calendar_event_id, document_id)
);
CREATE TABLE IF NOT EXISTS calendar_event_property_values (
	event_id INTEGER NOT NULL, 
	property_id INTEGER NOT NULL, 
	value_text TEXT, 
	value_number NUMERIC, 
	value_boolean BOOLEAN, 
	value_date DATE, 
	value_datetime TIMESTAMP WITH TIME ZONE, 
	value_user_id INTEGER, 
	value_json JSONB, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT calendar_event_property_values_pkey PRIMARY KEY (event_id, property_id)
);
CREATE TABLE IF NOT EXISTS calendar_event_tags (
	calendar_event_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT calendar_event_tags_pkey PRIMARY KEY (calendar_event_id, tag_id)
);
CREATE TABLE IF NOT EXISTS calendar_events (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	initiative_id INTEGER NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	description TEXT, 
	location VARCHAR(500), 
	start_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	end_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	all_day BOOLEAN DEFAULT false NOT NULL, 
	color VARCHAR(32), 
	recurrence TEXT, 
	created_by_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT calendar_events_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS comments (
	id SERIAL NOT NULL, 
	content TEXT NOT NULL, 
	author_id INTEGER NOT NULL, 
	task_id INTEGER, 
	document_id INTEGER, 
	parent_comment_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	guild_id INTEGER, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT comments_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS counter_group_permissions (
	counter_group_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	level counter_permission_level NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT counter_group_permissions_pkey PRIMARY KEY (counter_group_id, user_id)
);
CREATE TABLE IF NOT EXISTS counter_group_role_permissions (
	counter_group_id INTEGER NOT NULL, 
	initiative_role_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	level counter_permission_level NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT counter_group_role_permissions_pkey PRIMARY KEY (counter_group_id, initiative_role_id)
);
CREATE TABLE IF NOT EXISTS counter_groups (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	initiative_id INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	created_by_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT counter_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS counters (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	counter_group_id INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	color VARCHAR(32), 
	count NUMERIC(20, 10) DEFAULT '0'::numeric NOT NULL, 
	min NUMERIC(20, 10), 
	max NUMERIC(20, 10), 
	step NUMERIC(20, 10) DEFAULT '1'::numeric NOT NULL, 
	initial_count NUMERIC(20, 10) DEFAULT '0'::numeric NOT NULL, 
	view_mode counter_view_mode DEFAULT 'number'::counter_view_mode NOT NULL, 
	position NUMERIC(20, 10) DEFAULT '0'::numeric NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT counters_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS document_file_versions (
	id SERIAL NOT NULL, 
	document_id INTEGER NOT NULL, 
	guild_id INTEGER, 
	version_number INTEGER NOT NULL, 
	file_url VARCHAR(512) NOT NULL, 
	file_content_type VARCHAR(128), 
	file_size BIGINT, 
	original_filename VARCHAR(255), 
	uploaded_by_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT document_file_versions_pkey PRIMARY KEY (id), 
	CONSTRAINT uq_dfv_document_version UNIQUE (document_id, version_number)
);
CREATE TABLE IF NOT EXISTS document_links (
	source_document_id INTEGER NOT NULL, 
	target_document_id INTEGER NOT NULL, 
	guild_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT document_links_pkey PRIMARY KEY (source_document_id, target_document_id)
);
CREATE TABLE IF NOT EXISTS document_permissions (
	document_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	level document_permission_level NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL, 
	guild_id INTEGER NOT NULL, 
	CONSTRAINT document_permissions_pkey PRIMARY KEY (document_id, user_id)
);
CREATE TABLE IF NOT EXISTS document_property_values (
	document_id INTEGER NOT NULL, 
	property_id INTEGER NOT NULL, 
	value_text TEXT, 
	value_number NUMERIC, 
	value_boolean BOOLEAN, 
	value_date DATE, 
	value_datetime TIMESTAMP WITH TIME ZONE, 
	value_user_id INTEGER, 
	value_json JSONB, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT document_property_values_pkey PRIMARY KEY (document_id, property_id)
);
CREATE TABLE IF NOT EXISTS document_role_permissions (
	document_id INTEGER NOT NULL, 
	initiative_role_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	level document_permission_level DEFAULT 'read'::document_permission_level NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT document_role_permissions_pkey PRIMARY KEY (document_id, initiative_role_id)
);
CREATE TABLE IF NOT EXISTS document_tags (
	document_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT document_tags_pkey PRIMARY KEY (document_id, tag_id)
);
CREATE TABLE IF NOT EXISTS documents (
	id SERIAL NOT NULL, 
	initiative_id INTEGER NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	content JSONB DEFAULT '{}'::jsonb NOT NULL, 
	created_by_id INTEGER NOT NULL, 
	updated_by_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL, 
	featured_image_url VARCHAR(512), 
	is_template BOOLEAN NOT NULL, 
	yjs_state BYTEA, 
	yjs_updated_at TIMESTAMP WITH TIME ZONE, 
	guild_id INTEGER NOT NULL, 
	document_type document_type DEFAULT 'native'::document_type NOT NULL, 
	file_url VARCHAR(512), 
	file_content_type VARCHAR(128), 
	file_size BIGINT, 
	original_filename VARCHAR(255), 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT documents_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS event_reminder_dispatches (
	id SERIAL NOT NULL, 
	event_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	event_start_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	sent_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT event_reminder_dispatches_pkey PRIMARY KEY (id), 
	CONSTRAINT uq_event_reminder_dispatch UNIQUE (event_id, user_id, event_start_at)
);
CREATE TABLE IF NOT EXISTS guild_settings (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	ai_enabled BOOLEAN, 
	ai_provider VARCHAR(50), 
	ai_base_url VARCHAR(1000), 
	ai_model VARCHAR(500), 
	ai_allow_user_override BOOLEAN, 
	ai_api_key_encrypted VARCHAR(2000), 
	retention_days INTEGER DEFAULT 90, 
	CONSTRAINT guild_settings_pkey PRIMARY KEY (id), 
	CONSTRAINT guild_settings_guild_id_key UNIQUE (guild_id)
);
CREATE TABLE IF NOT EXISTS initiative_members (
	initiative_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	joined_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	guild_id INTEGER NOT NULL, 
	role_id INTEGER, 
	oidc_managed BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT team_members_pkey PRIMARY KEY (initiative_id, user_id)
);
CREATE TABLE IF NOT EXISTS initiative_role_permissions (
	initiative_role_id INTEGER NOT NULL, 
	permission_key VARCHAR(50) NOT NULL, 
	enabled BOOLEAN DEFAULT true NOT NULL, 
	CONSTRAINT initiative_role_permissions_pkey PRIMARY KEY (initiative_role_id, permission_key)
);
CREATE TABLE IF NOT EXISTS initiative_roles (
	id SERIAL NOT NULL, 
	initiative_id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	display_name VARCHAR(100) NOT NULL, 
	is_builtin BOOLEAN DEFAULT false NOT NULL, 
	is_manager BOOLEAN DEFAULT false NOT NULL, 
	position INTEGER DEFAULT 0 NOT NULL, 
	CONSTRAINT initiative_roles_pkey PRIMARY KEY (id), 
	CONSTRAINT uq_initiative_role_name UNIQUE (initiative_id, name)
);
CREATE TABLE IF NOT EXISTS initiatives (
	id SERIAL NOT NULL, 
	name VARCHAR NOT NULL, 
	description VARCHAR, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	color VARCHAR(32), 
	is_default BOOLEAN NOT NULL, 
	guild_id INTEGER NOT NULL, 
	queues_enabled BOOLEAN DEFAULT false NOT NULL, 
	events_enabled BOOLEAN DEFAULT false NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	advanced_tool_enabled BOOLEAN DEFAULT false NOT NULL, 
	counters_enabled BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT teams_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS project_documents (
	project_id INTEGER NOT NULL, 
	document_id INTEGER NOT NULL, 
	attached_by_id INTEGER, 
	attached_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL, 
	guild_id INTEGER NOT NULL, 
	CONSTRAINT project_documents_pkey PRIMARY KEY (project_id, document_id)
);
CREATE TABLE IF NOT EXISTS project_favorites (
	user_id INTEGER NOT NULL, 
	project_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	guild_id INTEGER NOT NULL, 
	CONSTRAINT project_favorites_pkey PRIMARY KEY (user_id, project_id)
);
CREATE TABLE IF NOT EXISTS project_orders (
	user_id INTEGER NOT NULL, 
	project_id INTEGER NOT NULL, 
	sort_order DOUBLE PRECISION DEFAULT '0'::double precision NOT NULL, 
	guild_id INTEGER NOT NULL, 
	CONSTRAINT project_orders_pkey PRIMARY KEY (user_id, project_id)
);
CREATE TABLE IF NOT EXISTS project_permissions (
	project_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	level project_permission_level NOT NULL, 
	guild_id INTEGER NOT NULL, 
	CONSTRAINT project_members_pkey PRIMARY KEY (project_id, user_id)
);
CREATE TABLE IF NOT EXISTS project_role_permissions (
	project_id INTEGER NOT NULL, 
	initiative_role_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	level project_permission_level DEFAULT 'read'::project_permission_level NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT project_role_permissions_pkey PRIMARY KEY (project_id, initiative_role_id)
);
CREATE TABLE IF NOT EXISTS project_tags (
	project_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT project_tags_pkey PRIMARY KEY (project_id, tag_id)
);
CREATE TABLE IF NOT EXISTS projects (
	id SERIAL NOT NULL, 
	name VARCHAR NOT NULL, 
	icon VARCHAR(8), 
	description TEXT, 
	owner_id INTEGER NOT NULL, 
	initiative_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	is_archived BOOLEAN NOT NULL, 
	is_template BOOLEAN NOT NULL, 
	archived_at TIMESTAMP WITH TIME ZONE, 
	pinned_at TIMESTAMP WITH TIME ZONE, 
	guild_id INTEGER NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS property_definitions (
	id SERIAL NOT NULL, 
	initiative_id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	type property_type NOT NULL, 
	position NUMERIC(20, 10) DEFAULT 0 NOT NULL, 
	color VARCHAR(9), 
	options JSONB, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT property_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS queue_item_documents (
	queue_item_id INTEGER NOT NULL, 
	document_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	attached_by_id INTEGER, 
	attached_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT queue_item_documents_pkey PRIMARY KEY (queue_item_id, document_id)
);
CREATE TABLE IF NOT EXISTS queue_item_tags (
	queue_item_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT queue_item_tags_pkey PRIMARY KEY (queue_item_id, tag_id)
);
CREATE TABLE IF NOT EXISTS queue_item_tasks (
	queue_item_id INTEGER NOT NULL, 
	task_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	attached_by_id INTEGER, 
	attached_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT queue_item_tasks_pkey PRIMARY KEY (queue_item_id, task_id)
);
CREATE TABLE IF NOT EXISTS queue_items (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	queue_id INTEGER NOT NULL, 
	label VARCHAR(255) NOT NULL, 
	position NUMERIC(20, 10) DEFAULT 0 NOT NULL, 
	user_id INTEGER, 
	color VARCHAR(32), 
	notes TEXT, 
	is_visible BOOLEAN DEFAULT true NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	held_at_round INTEGER, 
	CONSTRAINT queue_items_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS queue_permissions (
	queue_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	level queue_permission_level NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT queue_permissions_pkey PRIMARY KEY (queue_id, user_id)
);
CREATE TABLE IF NOT EXISTS queue_role_permissions (
	queue_id INTEGER NOT NULL, 
	initiative_role_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	level queue_permission_level NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT queue_role_permissions_pkey PRIMARY KEY (queue_id, initiative_role_id)
);
CREATE TABLE IF NOT EXISTS queues (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	initiative_id INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description VARCHAR, 
	created_by_id INTEGER NOT NULL, 
	current_round INTEGER DEFAULT 1 NOT NULL, 
	is_active BOOLEAN DEFAULT false NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	current_item_id INTEGER, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT queues_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS recent_views (
	user_id INTEGER NOT NULL, 
	entity_type TEXT NOT NULL, 
	entity_id INTEGER NOT NULL, 
	guild_id INTEGER, 
	last_viewed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT recent_views_pkey PRIMARY KEY (user_id, entity_type, entity_id)
);
CREATE TABLE IF NOT EXISTS subtasks (
	id SERIAL NOT NULL, 
	task_id INTEGER NOT NULL, 
	content TEXT NOT NULL, 
	is_completed BOOLEAN DEFAULT false NOT NULL, 
	position INTEGER DEFAULT 0 NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	guild_id INTEGER NOT NULL, 
	CONSTRAINT subtasks_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS tags (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	color VARCHAR(9) DEFAULT '#6366F1'::character varying NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT tags_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS task_assignees (
	task_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	guild_id INTEGER NOT NULL, 
	CONSTRAINT task_assignees_pkey PRIMARY KEY (task_id, user_id)
);
CREATE TABLE IF NOT EXISTS task_assignment_digest_items (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	task_id INTEGER NOT NULL, 
	project_id INTEGER NOT NULL, 
	task_title VARCHAR(255) NOT NULL, 
	project_name VARCHAR(255) NOT NULL, 
	assigned_by_name VARCHAR(255) NOT NULL, 
	assigned_by_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	processed_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT task_assignment_digest_items_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS task_property_values (
	task_id INTEGER NOT NULL, 
	property_id INTEGER NOT NULL, 
	value_text TEXT, 
	value_number NUMERIC, 
	value_boolean BOOLEAN, 
	value_date DATE, 
	value_datetime TIMESTAMP WITH TIME ZONE, 
	value_user_id INTEGER, 
	value_json JSONB, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT task_property_values_pkey PRIMARY KEY (task_id, property_id)
);
CREATE TABLE IF NOT EXISTS task_statuses (
	id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	position INTEGER DEFAULT 0 NOT NULL, 
	category task_status_category NOT NULL, 
	is_default BOOLEAN DEFAULT false NOT NULL, 
	guild_id INTEGER NOT NULL, 
	color VARCHAR(9) DEFAULT '#94A3B8'::character varying NOT NULL, 
	icon VARCHAR(64) DEFAULT 'circle-dashed'::character varying NOT NULL, 
	CONSTRAINT task_statuses_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS task_tags (
	task_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT task_tags_pkey PRIMARY KEY (task_id, tag_id)
);
CREATE TABLE IF NOT EXISTS tasks (
	id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	title VARCHAR NOT NULL, 
	description TEXT, 
	priority task_priority NOT NULL, 
	due_date TIMESTAMP WITH TIME ZONE, 
	position NUMERIC(20, 10) DEFAULT 0 NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	recurrence JSON, 
	recurrence_occurrence_count INTEGER NOT NULL, 
	start_date TIMESTAMP WITH TIME ZONE, 
	task_status_id INTEGER NOT NULL, 
	recurrence_strategy VARCHAR(20) NOT NULL, 
	is_archived BOOLEAN DEFAULT false NOT NULL, 
	guild_id INTEGER NOT NULL, 
	created_by_id INTEGER, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	deleted_by INTEGER, 
	purge_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT tasks_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS uploads (
	id SERIAL NOT NULL, 
	filename VARCHAR NOT NULL, 
	guild_id INTEGER NOT NULL, 
	uploader_user_id INTEGER NOT NULL, 
	size_bytes INTEGER DEFAULT 0 NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT uploads_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS webhook_subscriptions (
	id SERIAL NOT NULL, 
	guild_id INTEGER NOT NULL, 
	initiative_id INTEGER, 
	workflow_id INTEGER, 
	created_by_user_id INTEGER NOT NULL, 
	target_url VARCHAR(2048) NOT NULL, 
	hmac_secret VARCHAR(128) NOT NULL, 
	event_types VARCHAR(100)[] NOT NULL, 
	active BOOLEAN DEFAULT true NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT webhook_subscriptions_pkey PRIMARY KEY (id)
);

-- indexes
CREATE INDEX IF NOT EXISTS ix_calendar_event_attendees_user_id ON calendar_event_attendees USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_calendar_event_property_values_property_id ON calendar_event_property_values USING btree (property_id);
CREATE INDEX IF NOT EXISTS ix_calendar_event_property_values_property_json_gin ON calendar_event_property_values USING gin (value_json jsonb_path_ops) WHERE (value_json IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_event_property_values_property_value_date ON calendar_event_property_values USING btree (property_id, value_date) WHERE (value_date IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_event_property_values_property_value_datetime ON calendar_event_property_values USING btree (property_id, value_datetime) WHERE (value_datetime IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_event_property_values_property_value_number ON calendar_event_property_values USING btree (property_id, value_number) WHERE (value_number IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_event_property_values_property_value_text ON calendar_event_property_values USING btree (property_id, value_text) WHERE (value_text IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_event_property_values_property_value_user_id ON calendar_event_property_values USING btree (property_id, value_user_id) WHERE (value_user_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_event_tags_tag_id ON calendar_event_tags USING btree (tag_id);
CREATE INDEX IF NOT EXISTS ix_calendar_events_active ON calendar_events USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_events_guild_id ON calendar_events USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_calendar_events_initiative_id ON calendar_events USING btree (initiative_id);
CREATE INDEX IF NOT EXISTS ix_calendar_events_purge ON calendar_events USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_calendar_events_start_at ON calendar_events USING btree (start_at);
CREATE INDEX IF NOT EXISTS ix_comments_active ON comments USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_comments_author_id ON comments USING btree (author_id);
CREATE INDEX IF NOT EXISTS ix_comments_created_at ON comments USING btree (created_at);
CREATE INDEX IF NOT EXISTS ix_comments_document_id ON comments USING btree (document_id);
CREATE INDEX IF NOT EXISTS ix_comments_parent_comment_id ON comments USING btree (parent_comment_id);
CREATE INDEX IF NOT EXISTS ix_comments_purge ON comments USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_comments_task_id ON comments USING btree (task_id);
CREATE INDEX IF NOT EXISTS ix_counter_group_permissions_user_id ON counter_group_permissions USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_counter_groups_guild_id ON counter_groups USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_counter_groups_initiative_id ON counter_groups USING btree (initiative_id);
CREATE INDEX IF NOT EXISTS ix_counters_counter_group_id ON counters USING btree (counter_group_id);
CREATE INDEX IF NOT EXISTS ix_counters_group_position ON counters USING btree (counter_group_id, "position");
CREATE INDEX IF NOT EXISTS ix_counters_guild_id ON counters USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_document_file_versions_document_id ON document_file_versions USING btree (document_id);
CREATE INDEX IF NOT EXISTS ix_document_links_target_document_id ON document_links USING btree (target_document_id);
CREATE INDEX IF NOT EXISTS ix_document_permissions_guild_id ON document_permissions USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_document_permissions_user_id ON document_permissions USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_document_property_values_property_id ON document_property_values USING btree (property_id);
CREATE INDEX IF NOT EXISTS ix_document_property_values_property_json_gin ON document_property_values USING gin (value_json jsonb_path_ops) WHERE (value_json IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_document_property_values_property_value_date ON document_property_values USING btree (property_id, value_date) WHERE (value_date IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_document_property_values_property_value_datetime ON document_property_values USING btree (property_id, value_datetime) WHERE (value_datetime IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_document_property_values_property_value_number ON document_property_values USING btree (property_id, value_number) WHERE (value_number IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_document_property_values_property_value_text ON document_property_values USING btree (property_id, value_text) WHERE (value_text IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_document_property_values_property_value_user_id ON document_property_values USING btree (property_id, value_user_id) WHERE (value_user_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_document_tags_tag_id ON document_tags USING btree (tag_id);
CREATE INDEX IF NOT EXISTS idx_documents_updated_at ON documents USING btree (updated_at);
CREATE INDEX IF NOT EXISTS ix_documents_active ON documents USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_documents_guild_id ON documents USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_documents_initiative_id ON documents USING btree (initiative_id);
CREATE INDEX IF NOT EXISTS ix_documents_purge ON documents USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_documents_title ON documents USING btree (title);
CREATE INDEX IF NOT EXISTS ix_event_reminder_dispatches_event_id ON event_reminder_dispatches USING btree (event_id);
CREATE INDEX IF NOT EXISTS ix_event_reminder_dispatches_user_id ON event_reminder_dispatches USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_initiative_members_guild_id ON initiative_members USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_initiative_members_role_id ON initiative_members USING btree (role_id);
CREATE INDEX IF NOT EXISTS ix_initiative_members_user_id ON initiative_members USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_initiative_roles_initiative_id ON initiative_roles USING btree (initiative_id);
CREATE INDEX IF NOT EXISTS ix_initiatives_active ON initiatives USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_initiatives_guild_id ON initiatives USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_initiatives_name ON initiatives USING btree (name);
CREATE INDEX IF NOT EXISTS ix_initiatives_purge ON initiatives USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_initiatives_guild_default ON initiatives USING btree (guild_id) WHERE is_default;
CREATE UNIQUE INDEX IF NOT EXISTS uq_initiatives_guild_name ON initiatives USING btree (guild_id, lower((name)::text));
CREATE INDEX IF NOT EXISTS ix_project_documents_guild_id ON project_documents USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_project_favorites_guild_id ON project_favorites USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_project_favorites_project_id ON project_favorites USING btree (project_id);
CREATE INDEX IF NOT EXISTS ix_project_orders_guild_id ON project_orders USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_project_permissions_guild_id ON project_permissions USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_project_permissions_user_id ON project_permissions USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_project_tags_tag_id ON project_tags USING btree (tag_id);
CREATE INDEX IF NOT EXISTS ix_projects_active ON projects USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_projects_guild_id ON projects USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_projects_initiative_id ON projects USING btree (initiative_id);
CREATE INDEX IF NOT EXISTS ix_projects_name ON projects USING btree (name);
CREATE INDEX IF NOT EXISTS ix_projects_purge ON projects USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_property_definitions_initiative_id ON property_definitions USING btree (initiative_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_property_definitions_initiative_lower_name ON property_definitions USING btree (initiative_id, lower((name)::text));
CREATE INDEX IF NOT EXISTS ix_queue_item_tags_tag_id ON queue_item_tags USING btree (tag_id);
CREATE INDEX IF NOT EXISTS ix_queue_items_active ON queue_items USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_queue_items_guild_id ON queue_items USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_queue_items_purge ON queue_items USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_queue_items_queue_id ON queue_items USING btree (queue_id);
CREATE INDEX IF NOT EXISTS ix_queue_permissions_user_id ON queue_permissions USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_queues_active ON queues USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_queues_guild_id ON queues USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_queues_initiative_id ON queues USING btree (initiative_id);
CREATE INDEX IF NOT EXISTS ix_queues_purge ON queues USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_recent_views_entity ON recent_views USING btree (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_recent_views_guild_id ON recent_views USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_recent_views_user_last_viewed_at ON recent_views USING btree (user_id, last_viewed_at DESC);
CREATE INDEX IF NOT EXISTS ix_subtasks_guild_id ON subtasks USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_subtasks_task_id ON subtasks USING btree (task_id);
CREATE INDEX IF NOT EXISTS ix_tags_active ON tags USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_tags_guild_id ON tags USING btree (guild_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_tags_guild_name_unique ON tags USING btree (guild_id, lower((name)::text));
CREATE INDEX IF NOT EXISTS ix_tags_purge ON tags USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_task_assignees_guild_id ON task_assignees USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_task_assignees_user_id ON task_assignees USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_task_assignment_digest_items_unprocessed ON task_assignment_digest_items USING btree (processed_at) WHERE (processed_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_task_assignment_digest_items_user_id ON task_assignment_digest_items USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_task_property_values_property_id ON task_property_values USING btree (property_id);
CREATE INDEX IF NOT EXISTS ix_task_property_values_property_json_gin ON task_property_values USING gin (value_json jsonb_path_ops) WHERE (value_json IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_task_property_values_property_value_date ON task_property_values USING btree (property_id, value_date) WHERE (value_date IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_task_property_values_property_value_datetime ON task_property_values USING btree (property_id, value_datetime) WHERE (value_datetime IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_task_property_values_property_value_number ON task_property_values USING btree (property_id, value_number) WHERE (value_number IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_task_property_values_property_value_text ON task_property_values USING btree (property_id, value_text) WHERE (value_text IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_task_property_values_property_value_user_id ON task_property_values USING btree (property_id, value_user_id) WHERE (value_user_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS ix_task_statuses_guild_id ON task_statuses USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_task_statuses_project_position ON task_statuses USING btree (project_id, "position");
CREATE INDEX IF NOT EXISTS ix_task_tags_tag_id ON task_tags USING btree (tag_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date_status ON tasks USING btree (due_date, task_status_id) WHERE (due_date IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_tasks_project_archived ON tasks USING btree (project_id, is_archived);
CREATE INDEX IF NOT EXISTS idx_tasks_updated_at ON tasks USING btree (updated_at);
CREATE INDEX IF NOT EXISTS ix_tasks_active ON tasks USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_tasks_guild_id ON tasks USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_tasks_project_id_id ON tasks USING btree (project_id, id);
CREATE INDEX IF NOT EXISTS ix_tasks_purge ON tasks USING btree (purge_at) WHERE (purge_at IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS ix_uploads_filename ON uploads USING btree (filename);
CREATE INDEX IF NOT EXISTS ix_uploads_guild_id ON uploads USING btree (guild_id);
CREATE INDEX IF NOT EXISTS ix_webhook_subscriptions_dispatch ON webhook_subscriptions USING btree (guild_id, initiative_id) WHERE (active = true);
CREATE INDEX IF NOT EXISTS ix_webhook_subscriptions_guild_id ON webhook_subscriptions USING btree (guild_id);

-- CHECK constraints
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_comments_task_or_document' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "comments" ADD CONSTRAINT "ck_comments_task_or_document" CHECK (((task_id IS NULL) <> (document_id IS NULL))); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_initiative_role_permissions_permission_key' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "initiative_role_permissions" ADD CONSTRAINT "ck_initiative_role_permissions_permission_key" CHECK (((permission_key)::text = ANY ((ARRAY['docs_enabled'::character varying, 'projects_enabled'::character varying, 'create_docs'::character varying, 'create_projects'::character varying, 'queues_enabled'::character varying, 'create_queues'::character varying, 'events_enabled'::character varying, 'create_events'::character varying, 'advanced_tool_enabled'::character varying, 'create_advanced_tool'::character varying, 'counters_enabled'::character varying, 'create_counters'::character varying])::text[]))); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_recent_views_entity_type' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "recent_views" ADD CONSTRAINT "ck_recent_views_entity_type" CHECK ((entity_type = ANY (ARRAY['project'::text, 'document'::text, 'queue'::text, 'counter_group'::text]))); END IF; END $$;

-- intra-schema FOREIGN KEYs
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_event_attendees_calendar_event_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_event_attendees" ADD CONSTRAINT "calendar_event_attendees_calendar_event_id_fkey" FOREIGN KEY (calendar_event_id) REFERENCES calendar_events(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_event_documents_calendar_event_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_event_documents" ADD CONSTRAINT "calendar_event_documents_calendar_event_id_fkey" FOREIGN KEY (calendar_event_id) REFERENCES calendar_events(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_event_documents_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_event_documents" ADD CONSTRAINT "calendar_event_documents_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_event_property_values_event_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_event_property_values" ADD CONSTRAINT "calendar_event_property_values_event_id_fkey" FOREIGN KEY (event_id) REFERENCES calendar_events(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_event_property_values_property_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_event_property_values" ADD CONSTRAINT "calendar_event_property_values_property_id_fkey" FOREIGN KEY (property_id) REFERENCES property_definitions(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_event_tags_calendar_event_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_event_tags" ADD CONSTRAINT "calendar_event_tags_calendar_event_id_fkey" FOREIGN KEY (calendar_event_id) REFERENCES calendar_events(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_event_tags_tag_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_event_tags" ADD CONSTRAINT "calendar_event_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'calendar_events_initiative_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "calendar_events" ADD CONSTRAINT "calendar_events_initiative_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "comments" ADD CONSTRAINT "comments_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_parent_comment_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "comments" ADD CONSTRAINT "comments_parent_comment_id_fkey" FOREIGN KEY (parent_comment_id) REFERENCES comments(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_task_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "comments" ADD CONSTRAINT "comments_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'counter_group_permissions_counter_group_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "counter_group_permissions" ADD CONSTRAINT "counter_group_permissions_counter_group_id_fkey" FOREIGN KEY (counter_group_id) REFERENCES counter_groups(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'counter_group_role_permissions_counter_group_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "counter_group_role_permissions" ADD CONSTRAINT "counter_group_role_permissions_counter_group_id_fkey" FOREIGN KEY (counter_group_id) REFERENCES counter_groups(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'counter_group_role_permissions_initiative_role_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "counter_group_role_permissions" ADD CONSTRAINT "counter_group_role_permissions_initiative_role_id_fkey" FOREIGN KEY (initiative_role_id) REFERENCES initiative_roles(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'counter_groups_initiative_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "counter_groups" ADD CONSTRAINT "counter_groups_initiative_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'counters_counter_group_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "counters" ADD CONSTRAINT "counters_counter_group_id_fkey" FOREIGN KEY (counter_group_id) REFERENCES counter_groups(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_file_versions_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_file_versions" ADD CONSTRAINT "document_file_versions_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_links_source_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_links" ADD CONSTRAINT "document_links_source_document_id_fkey" FOREIGN KEY (source_document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_links_target_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_links" ADD CONSTRAINT "document_links_target_document_id_fkey" FOREIGN KEY (target_document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_permissions_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_permissions" ADD CONSTRAINT "document_permissions_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_property_values_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_property_values" ADD CONSTRAINT "document_property_values_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_property_values_property_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_property_values" ADD CONSTRAINT "document_property_values_property_id_fkey" FOREIGN KEY (property_id) REFERENCES property_definitions(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_role_permissions_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_role_permissions" ADD CONSTRAINT "document_role_permissions_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_role_permissions_initiative_role_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_role_permissions" ADD CONSTRAINT "document_role_permissions_initiative_role_id_fkey" FOREIGN KEY (initiative_role_id) REFERENCES initiative_roles(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_tags_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_tags" ADD CONSTRAINT "document_tags_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_tags_tag_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "document_tags" ADD CONSTRAINT "document_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'documents_initiative_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "documents" ADD CONSTRAINT "documents_initiative_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_reminder_dispatches_event_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "event_reminder_dispatches" ADD CONSTRAINT "event_reminder_dispatches_event_id_fkey" FOREIGN KEY (event_id) REFERENCES calendar_events(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'initiative_members_role_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "initiative_members" ADD CONSTRAINT "initiative_members_role_id_fkey" FOREIGN KEY (role_id) REFERENCES initiative_roles(id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_members_team_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "initiative_members" ADD CONSTRAINT "team_members_team_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'initiative_role_permissions_initiative_role_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "initiative_role_permissions" ADD CONSTRAINT "initiative_role_permissions_initiative_role_id_fkey" FOREIGN KEY (initiative_role_id) REFERENCES initiative_roles(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'initiative_roles_initiative_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "initiative_roles" ADD CONSTRAINT "initiative_roles_initiative_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_documents_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_documents" ADD CONSTRAINT "project_documents_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_documents_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_documents" ADD CONSTRAINT "project_documents_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_favorites_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_favorites" ADD CONSTRAINT "project_favorites_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_orders_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_orders" ADD CONSTRAINT "project_orders_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_members_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_permissions" ADD CONSTRAINT "project_members_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_role_permissions_initiative_role_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_role_permissions" ADD CONSTRAINT "project_role_permissions_initiative_role_id_fkey" FOREIGN KEY (initiative_role_id) REFERENCES initiative_roles(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_role_permissions_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_role_permissions" ADD CONSTRAINT "project_role_permissions_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_tags_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_tags" ADD CONSTRAINT "project_tags_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'project_tags_tag_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "project_tags" ADD CONSTRAINT "project_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projects_team_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "projects" ADD CONSTRAINT "projects_team_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'property_definitions_initiative_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "property_definitions" ADD CONSTRAINT "property_definitions_initiative_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_item_documents_document_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_item_documents" ADD CONSTRAINT "queue_item_documents_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_item_documents_queue_item_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_item_documents" ADD CONSTRAINT "queue_item_documents_queue_item_id_fkey" FOREIGN KEY (queue_item_id) REFERENCES queue_items(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_item_tags_queue_item_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_item_tags" ADD CONSTRAINT "queue_item_tags_queue_item_id_fkey" FOREIGN KEY (queue_item_id) REFERENCES queue_items(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_item_tags_tag_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_item_tags" ADD CONSTRAINT "queue_item_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_item_tasks_queue_item_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_item_tasks" ADD CONSTRAINT "queue_item_tasks_queue_item_id_fkey" FOREIGN KEY (queue_item_id) REFERENCES queue_items(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_item_tasks_task_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_item_tasks" ADD CONSTRAINT "queue_item_tasks_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_items_queue_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_items" ADD CONSTRAINT "queue_items_queue_id_fkey" FOREIGN KEY (queue_id) REFERENCES queues(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_permissions_queue_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_permissions" ADD CONSTRAINT "queue_permissions_queue_id_fkey" FOREIGN KEY (queue_id) REFERENCES queues(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_role_permissions_initiative_role_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_role_permissions" ADD CONSTRAINT "queue_role_permissions_initiative_role_id_fkey" FOREIGN KEY (initiative_role_id) REFERENCES initiative_roles(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queue_role_permissions_queue_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queue_role_permissions" ADD CONSTRAINT "queue_role_permissions_queue_id_fkey" FOREIGN KEY (queue_id) REFERENCES queues(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_queues_current_item_id' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queues" ADD CONSTRAINT "fk_queues_current_item_id" FOREIGN KEY (current_item_id) REFERENCES queue_items(id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'queues_initiative_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "queues" ADD CONSTRAINT "queues_initiative_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subtasks_task_id' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "subtasks" ADD CONSTRAINT "fk_subtasks_task_id" FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_assignees_task_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_assignees" ADD CONSTRAINT "task_assignees_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_assignment_digest_items_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_assignment_digest_items" ADD CONSTRAINT "task_assignment_digest_items_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_assignment_digest_items_task_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_assignment_digest_items" ADD CONSTRAINT "task_assignment_digest_items_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_property_values_property_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_property_values" ADD CONSTRAINT "task_property_values_property_id_fkey" FOREIGN KEY (property_id) REFERENCES property_definitions(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_property_values_task_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_property_values" ADD CONSTRAINT "task_property_values_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_statuses_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_statuses" ADD CONSTRAINT "task_statuses_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_tags_tag_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_tags" ADD CONSTRAINT "task_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_tags_task_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "task_tags" ADD CONSTRAINT "task_tags_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tasks_task_status_id' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_task_status_id" FOREIGN KEY (task_status_id) REFERENCES task_statuses(id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tasks_project_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "tasks" ADD CONSTRAINT "tasks_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'webhook_subscriptions_initiative_id_fkey' AND connamespace = current_schema()::regnamespace) THEN ALTER TABLE "webhook_subscriptions" ADD CONSTRAINT "webhook_subscriptions_initiative_id_fkey" FOREIGN KEY (initiative_id) REFERENCES initiatives(id) ON DELETE CASCADE; END IF; END $$;

-- guild_id denormalization triggers (functions are shared in public)
CREATE OR REPLACE TRIGGER tr_comments_set_guild_id BEFORE INSERT OR UPDATE OF task_id, document_id ON comments FOR EACH ROW EXECUTE FUNCTION fn_comments_set_guild_id();
CREATE OR REPLACE TRIGGER tr_document_permissions_set_guild_id BEFORE INSERT OR UPDATE OF document_id ON document_permissions FOR EACH ROW EXECUTE FUNCTION fn_document_permissions_set_guild_id();
CREATE OR REPLACE TRIGGER tr_documents_set_guild_id BEFORE INSERT OR UPDATE OF initiative_id ON documents FOR EACH ROW EXECUTE FUNCTION fn_documents_set_guild_id();
CREATE OR REPLACE TRIGGER tr_initiative_members_set_guild_id BEFORE INSERT OR UPDATE OF initiative_id ON initiative_members FOR EACH ROW EXECUTE FUNCTION fn_initiative_members_set_guild_id();
CREATE OR REPLACE TRIGGER tr_project_documents_set_guild_id BEFORE INSERT OR UPDATE OF project_id ON project_documents FOR EACH ROW EXECUTE FUNCTION fn_project_documents_set_guild_id();
CREATE OR REPLACE TRIGGER tr_project_favorites_set_guild_id BEFORE INSERT OR UPDATE OF project_id ON project_favorites FOR EACH ROW EXECUTE FUNCTION fn_project_favorites_set_guild_id();
CREATE OR REPLACE TRIGGER tr_project_orders_set_guild_id BEFORE INSERT OR UPDATE OF project_id ON project_orders FOR EACH ROW EXECUTE FUNCTION fn_project_orders_set_guild_id();
CREATE OR REPLACE TRIGGER tr_project_permissions_set_guild_id BEFORE INSERT OR UPDATE OF project_id ON project_permissions FOR EACH ROW EXECUTE FUNCTION fn_project_permissions_set_guild_id();
CREATE OR REPLACE TRIGGER tr_projects_set_guild_id BEFORE INSERT OR UPDATE OF initiative_id ON projects FOR EACH ROW EXECUTE FUNCTION fn_projects_set_guild_id();
CREATE OR REPLACE TRIGGER tr_recent_views_set_guild_id BEFORE INSERT OR UPDATE OF entity_type, entity_id ON recent_views FOR EACH ROW EXECUTE FUNCTION fn_recent_views_set_guild_id();
CREATE OR REPLACE TRIGGER tr_subtasks_set_guild_id BEFORE INSERT OR UPDATE OF task_id ON subtasks FOR EACH ROW EXECUTE FUNCTION fn_subtasks_set_guild_id();
CREATE OR REPLACE TRIGGER tr_task_assignees_set_guild_id BEFORE INSERT OR UPDATE OF task_id ON task_assignees FOR EACH ROW EXECUTE FUNCTION fn_task_assignees_set_guild_id();
CREATE OR REPLACE TRIGGER tr_task_statuses_set_guild_id BEFORE INSERT OR UPDATE OF project_id ON task_statuses FOR EACH ROW EXECUTE FUNCTION fn_task_statuses_set_guild_id();
CREATE OR REPLACE TRIGGER tr_tasks_set_guild_id BEFORE INSERT OR UPDATE OF project_id ON tasks FOR EACH ROW EXECUTE FUNCTION fn_tasks_set_guild_id();
