from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Column,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    REAL,
    String,
    text,
)
from sqlmodel import Field, SQLModel

from app.core.relationships import (
    ENDPOINT_KIND_VALUES,
    PROVENANCES,
    SUBTYPES,
    SYMMETRIC_TYPES,
    RelationshipType,
)

#: Vocabularies frozen into CHECK constraints from the registries, so a column
#: can never hold a value nothing knows how to read or authorize.
_KIND_VALUES = ", ".join(f"'{value}'" for value in ENDPOINT_KIND_VALUES)
_TYPE_VALUES = ", ".join(f"'{t.value}'" for t in RelationshipType)
_PROVENANCE_VALUES = ", ".join(f"'{p.value}'" for p in PROVENANCES)
_SYMMETRIC_VALUES = ", ".join(f"'{t.value}'" for t in sorted(SYMMETRIC_TYPES))

#: Ships as ``subtype IS NULL``: the registry is empty, so the column is
#: reserved rather than usable, and the constraint says exactly that.
_SUBTYPE_CHECK = (
    f"subtype IS NULL OR subtype IN ({', '.join(repr(s) for s in sorted(SUBTYPES))})"
    if SUBTYPES
    else "subtype IS NULL"
)


def _node_expression(side: str) -> str:
    """The generated node id for one end.

    ``public.relationship_kind_code`` is an IMMUTABLE function rather than an
    inlined CASE, which is what makes admitting a new kind a
    ``CREATE OR REPLACE FUNCTION`` instead of a table rewrite in every guild
    schema. Existing rows keep their values because a kind's code never changes
    — the permanence rule in ``app.core.relationships`` is what makes that safe.
    """
    return f"(public.relationship_kind_code({side}_type) << 32) | {side}_id::bigint"


class EntityRelationship(SQLModel, table=True):
    """One edge: ``source -> relationship_type -> target``.

    Polymorphic on both ends, like ``resource_grants`` and ``reactions``, so a
    new kind of thing to connect costs a registry entry rather than a table. The
    row says what two things are to each other and how we came to know it — and
    nothing about the shape of the graph they form.

    **The table records; the shape is read.** There is no constraint here saying
    a hierarchy is a tree, that a part has one whole, or that dependencies do
    not loop. Those are one feature's reading of the graph and live in that
    feature: a picker that offers a single parent replaces the edge it manages,
    and a dependency picker warns about a loop it finds at read time. An edge
    arriving from content or from an accepted suggestion must not fail because
    of a rule written for a picker, and a loop two people believed in is a fact
    about their work worth keeping.

    Addressing is ``(type, id)``; the ``*_node`` columns are the same pair
    packed into one integer, generated by the database. They carry the
    constraints and the walk because a scalar is narrower to index, cheaper to
    join per hop, and gives the recursive CYCLE clause a plain ``bigint[]`` path
    instead of an array of records. ``source_type`` / ``source_id`` remain the
    truth a policy and a person read, and the generated columns cannot disagree
    with them.
    """

    __tablename__ = "relationships"
    __table_args__ = (
        CheckConstraint(
            f"source_type IN ({_KIND_VALUES})", name="ck_relationships_source_type"
        ),
        CheckConstraint(
            f"target_type IN ({_KIND_VALUES})", name="ck_relationships_target_type"
        ),
        CheckConstraint(
            f"relationship_type IN ({_TYPE_VALUES})", name="ck_relationships_type"
        ),
        CheckConstraint(_SUBTYPE_CHECK, name="ck_relationships_subtype"),
        CheckConstraint(
            f"provenance IN ({_PROVENANCE_VALUES})", name="ck_relationships_provenance"
        ),
        # Confidence belongs to an inferred edge and to no other kind.
        CheckConstraint(
            "(provenance = 'inferred') = (confidence IS NOT NULL)",
            name="ck_relationships_confidence",
        ),
        # Nothing in this vocabulary means anything from a thing to itself.
        CheckConstraint(
            "source_node <> target_node", name="ck_relationships_no_self_loop"
        ),
        # A symmetric relation describes neither end, so it is stored once, in
        # node-id order. One row per unordered pair, and the constraint says so.
        CheckConstraint(
            f"relationship_type NOT IN ({_SYMMETRIC_VALUES}) "
            "OR source_node < target_node",
            name="ck_relationships_symmetric_order",
        ),
        # Identity, over live rows only: a tombstoned edge does not block the
        # same pair being linked again.
        Index(
            "uq_relationships_edge",
            "source_node",
            "relationship_type",
            "target_node",
            unique=True,
            postgresql_where=text("removed_at IS NULL"),
        ),
        # The inverse read: every edge pointing AT something.
        Index(
            "ix_relationships_target",
            "target_node",
            "relationship_type",
            postgresql_where=text("removed_at IS NULL"),
        ),
    )

    id: Optional[int] = Field(
        default=None, sa_column=Column(BigInteger, primary_key=True)
    )
    #: Filled by trigger from the source endpoint. RLS does not read it — the
    #: schema is the tenant boundary — but cross-guild reads filter on it, so it
    #: is derived in the database where no write path can forget.
    guild_id: Optional[int] = Field(
        default=None,
        sa_column=Column(Integer, ForeignKey("guilds.id"), nullable=True),
    )

    source_type: str = Field(sa_column=Column(String(32), nullable=False))
    source_id: int = Field(sa_column=Column(Integer, nullable=False))
    relationship_type: str = Field(sa_column=Column(String(32), nullable=False))
    #: A finer word for an edge that obeys its primitive's rule. Ships unused;
    #: the column exists so the API and read schemas do not move when the first
    #: subtype lands.
    subtype: Optional[str] = Field(
        default=None, sa_column=Column(String(32), nullable=True)
    )
    target_type: str = Field(sa_column=Column(String(32), nullable=False))
    target_id: int = Field(sa_column=Column(Integer, nullable=False))

    source_node: Optional[int] = Field(
        default=None,
        sa_column=Column(
            BigInteger,
            Computed(_node_expression("source"), persisted=True),
            nullable=False,
        ),
    )
    target_node: Optional[int] = Field(
        default=None,
        sa_column=Column(
            BigInteger,
            Computed(_node_expression("target"), persisted=True),
            nullable=False,
        ),
    )

    #: How we know. Server-assigned per code path, never taken from a request:
    #: it is the sample weight any future scoring reads, and it decides whether
    #: a removal is remembered.
    provenance: str = Field(sa_column=Column(String(16), nullable=False))
    confidence: Optional[float] = Field(
        default=None, sa_column=Column(REAL, nullable=True)
    )

    created_by: int = Field(
        sa_column=Column(
            Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )

    #: A tombstone, not a trash entry. There is no restore and nothing reads a
    #: removed row on the request path; what it keeps is the one thing a delete
    #: destroys irrecoverably — that a person linked two things and then took it
    #: back. Only a MANUAL removal tombstones: an edge withdrawn because someone
    #: edited the sentence that implied it asserts nothing.
    removed_at: Optional[datetime] = Field(
        default=None, sa_column=Column(DateTime(timezone=True), nullable=True)
    )
    removed_by: Optional[int] = Field(
        default=None,
        sa_column=Column(
            Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
        ),
    )
